#include <windows.h>
#include <stdio.h>
#include <string.h>
typedef unsigned char u8;typedef unsigned u32;typedef u8 H[32];
extern __declspec(dllimport) void cont(void);extern __declspec(dllimport) int cvm_resolve_payload_hash(const H,H);extern __declspec(dllimport) u8*cvm_cached_base(void);extern __declspec(dllimport) u32 cvm_cached_len(void);
#include "../uistate.h"
#include "../dxgfx.h"
static int zero(u8*p){for(int i=0;i<32;i++)if(p[i])return 0;return 1;}static int same(H a,H b){return !memcmp(a,b,32);}static u32 sz(u8*p){return 36+*(u32*)(p+32);}static int valid(u8*b,u32 n,u32 o){return o+36<=n&&!zero(b+o)&&o+sz(b+o)<=n;}
static const char*name(UiState*s,H h){for(u32 i=0;i<s->reg_count;i++)if(!s->reg[i].tag&&same(s->reg[i].token,h))return s->reg[i].name;static char x[12];snprintf(x,sizeof(x),"%02x%02x%02x%02x",h[0],h[1],h[2],h[3]);return x;}
static void txt(int x,int y,u32 c,float z,const char*s){dxgfx_draw_text(x,y,c,z,s,(u32)strlen(s));}
static void view(UiState*s,u32 vi,float mx,float my,int press){UiView*v=&s->views[vi];H h;cvm_resolve_payload_hash(v->key,h);u8*b=cvm_cached_base();u32 n=cvm_cached_len();float x=v->x,y=v->y;if(v->linked&&v->parent>=0&&(u32)v->parent<s->view_count)dxgfx_draw_line(s->views[v->parent].x+v->link_x,s->views[v->parent].y+v->link_y,x,y,0xff62c982,2);char title[80];snprintf(title,sizeof(title),"[%u] %02x%02x%02x%02x",vi,v->key[0],v->key[1],v->key[2],v->key[3]);txt((int)x,(int)y-28,0xff9da7b3,16,title);if(mx>=x&&mx<x+520&&my>=y-32&&my<y&&press&2){s->active_view=vi;s->dragging_view=(int)vi;}u32 o=0;float ry=y;while(valid(b,n,o)){const char*nm=name(s,b+o);float w=170;if(mx>=x&&mx<x+520&&my>=ry&&my<ry+24){if(press&1){s->active_view=vi;s->point_off=o;}if(press&2&&s->view_count<UI_MAX_VIEWS){UiView*nv=&s->views[s->view_count];memset(nv,0,sizeof(*nv));nv->used=1;memcpy(nv->key,b+o,32);nv->x=mx;nv->y=my;nv->linked=1;nv->parent=(int)vi;nv->link_x=80;nv->link_y=ry-y+10;s->active_view=s->view_count;s->dragging_view=(int)s->view_count;s->view_count++;}}if(vi==s->active_view&&o==s->point_off)dxgfx_draw_rect(x-7,ry-2,510,23,0xff34414d,1,1);txt((int)x,(int)ry,0xffe8ecef,17,nm);u32 pn=*(u32*)(b+o+32);if(pn){char q[100];int printable=1;u32 z=pn<42?pn:42;for(u32 j=0;j<z;j++)if(b[o+36+j]<32||b[o+36+j]>126)printable=0;if(printable)snprintf(q,sizeof(q),"'%.*s'",(int)z,b+o+36);else snprintf(q,sizeof(q),"[%u bytes]",pn);txt((int)x+190,(int)ry,0xff7fb8d8,15,q);}ry+=24;o+=sz(b+o);}if(mx>=x&&mx<x+100&&my>=ry&&my<ry+24&&(press&1)){s->active_view=vi;s->point_off=o;}if(vi==s->active_view&&o==s->point_off)dxgfx_draw_rect(x-7,ry-2,90,23,0xff34414d,1,1);txt((int)x,(int)ry,0xff66717d,16,"<end>");}
__declspec(dllexport) void run(void){UiState*s=ui_state();int*m=s->mouse;float*wm=s->world_mouse;dxgfx_set_camera(s->cam_x,s->cam_y,s->zoom);dxgfx_world_mouse(wm);for(u32 i=0;i<s->view_count;i++)if(s->views[i].used)view(s,i,wm[0],wm[1],m[3]);dxgfx_set_camera(640,360,1);char hud[420];snprintf(hud,sizeof(hud),"%s%s%s",s->input,s->completion,s->dirty?" *":"");dxgfx_draw_rect(12,12,520,30,0xdd171b1f,1,1);txt(20,17,0xffffffff,17,hud);char status[100];snprintf(status,sizeof(status),"%u commands  view %u/%u",s->reg_count,s->active_view+1,s->view_count);txt(20,48,0xff73808c,14,status);cont();}
