Package( InitWindow__,InitWindow( *(int *)(std), *(int *)(std + sizeof(int )), *(const char **)(std + sizeof(int ) + sizeof(int )));)
Package( CloseWindow__,CloseWindow();)
Package( WindowShouldClose__,*(bool*)(std) = WindowShouldClose();std += sizeof(bool);)
Package( IsWindowReady__,*(bool*)(std) = IsWindowReady();std += sizeof(bool);)
Package( IsWindowFullscreen__,*(bool*)(std) = IsWindowFullscreen();std += sizeof(bool);)
Package( IsWindowHidden__,*(bool*)(std) = IsWindowHidden();std += sizeof(bool);)
Package( IsWindowMinimized__,*(bool*)(std) = IsWindowMinimized();std += sizeof(bool);)
Package( IsWindowMaximized__,*(bool*)(std) = IsWindowMaximized();std += sizeof(bool);)
Package( IsWindowFocused__,*(bool*)(std) = IsWindowFocused();std += sizeof(bool);)
Package( IsWindowResized__,*(bool*)(std) = IsWindowResized();std += sizeof(bool);)
Package( IsWindowState__,*(bool*)(std) = IsWindowState( *(unsigned int *)(std));std += sizeof(bool);)
Package( SetWindowState__,SetWindowState( *(unsigned int *)(std));)
Package( ClearWindowState__,ClearWindowState( *(unsigned int *)(std));)
Package( ToggleFullscreen__,ToggleFullscreen();)
Package( ToggleBorderlessWindowed__,ToggleBorderlessWindowed();)
Package( MaximizeWindow__,MaximizeWindow();)
Package( MinimizeWindow__,MinimizeWindow();)
Package( RestoreWindow__,RestoreWindow();)
Package( SetWindowIcon__,SetWindowIcon( *(Image *)(std));)
Package( SetWindowIcons__,SetWindowIcons( *(Image **)(std), *(int *)(std + sizeof(Image *)));)
Package( SetWindowTitle__,SetWindowTitle( *(const char **)(std));)
Package( SetWindowPosition__,SetWindowPosition( *(int *)(std), *(int *)(std + sizeof(int )));)
Package( SetWindowMonitor__,SetWindowMonitor( *(int *)(std));)
Package( SetWindowMinSize__,SetWindowMinSize( *(int *)(std), *(int *)(std + sizeof(int )));)
Package( SetWindowMaxSize__,SetWindowMaxSize( *(int *)(std), *(int *)(std + sizeof(int )));)
Package( SetWindowSize__,SetWindowSize( *(int *)(std), *(int *)(std + sizeof(int )));)
Package( SetWindowOpacity__,SetWindowOpacity( *(float *)(std));)
Package( SetWindowFocused__,SetWindowFocused();)
Package( GetWindowHandle__,*(void **)(std) = GetWindowHandle();std += sizeof(void *);)
Package( GetScreenWidth__,*(int*)(std) = GetScreenWidth();std += sizeof(int);)
Package( GetScreenHeight__,*(int*)(std) = GetScreenHeight();std += sizeof(int);)
Package( GetRenderWidth__,*(int*)(std) = GetRenderWidth();std += sizeof(int);)
Package( GetRenderHeight__,*(int*)(std) = GetRenderHeight();std += sizeof(int);)
Package( GetMonitorCount__,*(int*)(std) = GetMonitorCount();std += sizeof(int);)
Package( GetCurrentMonitor__,*(int*)(std) = GetCurrentMonitor();std += sizeof(int);)
Package( GetMonitorPosition__,*(Vector2*)(std) = GetMonitorPosition( *(int *)(std));std += sizeof(Vector2);)
Package( GetMonitorWidth__,*(int*)(std) = GetMonitorWidth( *(int *)(std));std += sizeof(int);)
Package( GetMonitorHeight__,*(int*)(std) = GetMonitorHeight( *(int *)(std));std += sizeof(int);)
Package( GetMonitorPhysicalWidth__,*(int*)(std) = GetMonitorPhysicalWidth( *(int *)(std));std += sizeof(int);)
Package( GetMonitorPhysicalHeight__,*(int*)(std) = GetMonitorPhysicalHeight( *(int *)(std));std += sizeof(int);)
Package( GetMonitorRefreshRate__,*(int*)(std) = GetMonitorRefreshRate( *(int *)(std));std += sizeof(int);)
Package( GetWindowPosition__,*(Vector2*)(std) = GetWindowPosition();std += sizeof(Vector2);)
Package( GetWindowScaleDPI__,*(Vector2*)(std) = GetWindowScaleDPI();std += sizeof(Vector2);)
Package( GetMonitorName__,*(const char **)(std) = GetMonitorName( *(int *)(std));std += sizeof(const char *);)
Package( SetClipboardText__,SetClipboardText( *(const char **)(std));)
Package( GetClipboardText__,*(const char **)(std) = GetClipboardText();std += sizeof(const char *);)
Package( GetClipboardImage__,*(Image*)(std) = GetClipboardImage();std += sizeof(Image);)
Package( EnableEventWaiting__,EnableEventWaiting();)
Package( DisableEventWaiting__,DisableEventWaiting();)
Package( ShowCursor__,ShowCursor();)
Package( HideCursor__,HideCursor();)
Package( IsCursorHidden__,*(bool*)(std) = IsCursorHidden();std += sizeof(bool);)
Package( EnableCursor__,EnableCursor();)
Package( DisableCursor__,DisableCursor();)
Package( IsCursorOnScreen__,*(bool*)(std) = IsCursorOnScreen();std += sizeof(bool);)
Package( ClearBackground__,ClearBackground( *(Color *)(std));)
Package( BeginDrawing__,BeginDrawing();)
Package( EndDrawing__,EndDrawing();)
Package( BeginMode2D__,BeginMode2D( *(Camera2D *)(std));)
Package( EndMode2D__,EndMode2D();)
Package( BeginMode3D__,BeginMode3D( *(Camera3D *)(std));)
Package( EndMode3D__,EndMode3D();)
Package( BeginTextureMode__,BeginTextureMode( *(RenderTexture2D *)(std));)
Package( EndTextureMode__,EndTextureMode();)
Package( BeginShaderMode__,BeginShaderMode( *(Shader *)(std));)
Package( EndShaderMode__,EndShaderMode();)
Package( BeginBlendMode__,BeginBlendMode( *(int *)(std));)
Package( EndBlendMode__,EndBlendMode();)
Package( BeginScissorMode__,BeginScissorMode( *(int *)(std), *(int *)(std + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int ) + sizeof(int )));)
Package( EndScissorMode__,EndScissorMode();)
Package( BeginVrStereoMode__,BeginVrStereoMode( *(VrStereoConfig *)(std));)
Package( EndVrStereoMode__,EndVrStereoMode();)
Package( LoadVrStereoConfig__,*(VrStereoConfig*)(std) = LoadVrStereoConfig( *(VrDeviceInfo *)(std));std += sizeof(VrStereoConfig);)
Package( UnloadVrStereoConfig__,UnloadVrStereoConfig( *(VrStereoConfig *)(std));)
Package( LoadShader__,*(Shader*)(std) = LoadShader( *(const char **)(std), *(const char **)(std + sizeof(const char *)));std += sizeof(Shader);)
Package( LoadShaderFromMemory__,*(Shader*)(std) = LoadShaderFromMemory( *(const char **)(std), *(const char **)(std + sizeof(const char *)));std += sizeof(Shader);)
Package( IsShaderValid__,*(bool*)(std) = IsShaderValid( *(Shader *)(std));std += sizeof(bool);)
Package( GetShaderLocation__,*(int*)(std) = GetShaderLocation( *(Shader *)(std), *(const char **)(std + sizeof(Shader )));std += sizeof(int);)
Package( GetShaderLocationAttrib__,*(int*)(std) = GetShaderLocationAttrib( *(Shader *)(std), *(const char **)(std + sizeof(Shader )));std += sizeof(int);)
Package( SetShaderValue__,SetShaderValue( *(Shader *)(std), *(int *)(std + sizeof(Shader )), *(const void **)(std + sizeof(Shader ) + sizeof(int )), *(int *)(std + sizeof(Shader ) + sizeof(int ) + sizeof(const void *)));)
Package( SetShaderValueV__,SetShaderValueV( *(Shader *)(std), *(int *)(std + sizeof(Shader )), *(const void **)(std + sizeof(Shader ) + sizeof(int )), *(int *)(std + sizeof(Shader ) + sizeof(int ) + sizeof(const void *)), *(int *)(std + sizeof(Shader ) + sizeof(int ) + sizeof(const void *) + sizeof(int )));)
Package( SetShaderValueMatrix__,SetShaderValueMatrix( *(Shader *)(std), *(int *)(std + sizeof(Shader )), *(Matrix *)(std + sizeof(Shader ) + sizeof(int )));)
Package( SetShaderValueTexture__,SetShaderValueTexture( *(Shader *)(std), *(int *)(std + sizeof(Shader )), *(Texture2D *)(std + sizeof(Shader ) + sizeof(int )));)
Package( UnloadShader__,UnloadShader( *(Shader *)(std));)
Package( GetScreenToWorldRay__,*(Ray*)(std) = GetScreenToWorldRay( *(Vector2 *)(std), *(Camera *)(std + sizeof(Vector2 )));std += sizeof(Ray);)
Package( GetScreenToWorldRayEx__,*(Ray*)(std) = GetScreenToWorldRayEx( *(Vector2 *)(std), *(Camera *)(std + sizeof(Vector2 )), *(int *)(std + sizeof(Vector2 ) + sizeof(Camera )), *(int *)(std + sizeof(Vector2 ) + sizeof(Camera ) + sizeof(int )));std += sizeof(Ray);)
Package( GetWorldToScreen__,*(Vector2*)(std) = GetWorldToScreen( *(Vector3 *)(std), *(Camera *)(std + sizeof(Vector3 )));std += sizeof(Vector2);)
Package( GetWorldToScreenEx__,*(Vector2*)(std) = GetWorldToScreenEx( *(Vector3 *)(std), *(Camera *)(std + sizeof(Vector3 )), *(int *)(std + sizeof(Vector3 ) + sizeof(Camera )), *(int *)(std + sizeof(Vector3 ) + sizeof(Camera ) + sizeof(int )));std += sizeof(Vector2);)
Package( GetWorldToScreen2D__,*(Vector2*)(std) = GetWorldToScreen2D( *(Vector2 *)(std), *(Camera2D *)(std + sizeof(Vector2 )));std += sizeof(Vector2);)
Package( GetScreenToWorld2D__,*(Vector2*)(std) = GetScreenToWorld2D( *(Vector2 *)(std), *(Camera2D *)(std + sizeof(Vector2 )));std += sizeof(Vector2);)
Package( GetCameraMatrix__,*(Matrix*)(std) = GetCameraMatrix( *(Camera *)(std));std += sizeof(Matrix);)
Package( GetCameraMatrix2D__,*(Matrix*)(std) = GetCameraMatrix2D( *(Camera2D *)(std));std += sizeof(Matrix);)
Package( SetTargetFPS__,SetTargetFPS( *(int *)(std));)
Package( GetFrameTime__,*(float*)(std) = GetFrameTime();std += sizeof(float);)
Package( GetTime__,*(double*)(std) = GetTime();std += sizeof(double);)
Package( GetFPS__,*(int*)(std) = GetFPS();std += sizeof(int);)
Package( SwapScreenBuffer__,SwapScreenBuffer();)
Package( PollInputEvents__,PollInputEvents();)
Package( WaitTime__,WaitTime( *(double *)(std));)
Package( SetRandomSeed__,SetRandomSeed( *(unsigned int *)(std));)
Package( GetRandomValue__,*(int*)(std) = GetRandomValue( *(int *)(std), *(int *)(std + sizeof(int )));std += sizeof(int);)
Package( LoadRandomSequence__,*(int **)(std) = LoadRandomSequence( *(unsigned int *)(std), *(int *)(std + sizeof(unsigned int )), *(int *)(std + sizeof(unsigned int ) + sizeof(int )));std += sizeof(int *);)
Package( UnloadRandomSequence__,UnloadRandomSequence( *(int **)(std));)
Package( TakeScreenshot__,TakeScreenshot( *(const char **)(std));)
Package( SetConfigFlags__,SetConfigFlags( *(unsigned int *)(std));)
Package( OpenURL__,OpenURL( *(const char **)(std));)
Package( TraceLog__,TraceLog( *(int *)(std), *(const char **)(std + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(const char *)));)
Package( SetTraceLogLevel__,SetTraceLogLevel( *(int *)(std));)
Package( MemAlloc__,*(void **)(std) = MemAlloc( *(unsigned int *)(std));std += sizeof(void *);)
Package( MemRealloc__,*(void **)(std) = MemRealloc( *(void **)(std), *(unsigned int *)(std + sizeof(void *)));std += sizeof(void *);)
Package( MemFree__,MemFree( *(void **)(std));)
Package( SetTraceLogCallback__,SetTraceLogCallback( *(TraceLogCallback *)(std));)
Package( SetLoadFileDataCallback__,SetLoadFileDataCallback( *(LoadFileDataCallback *)(std));)
Package( SetSaveFileDataCallback__,SetSaveFileDataCallback( *(SaveFileDataCallback *)(std));)
Package( SetLoadFileTextCallback__,SetLoadFileTextCallback( *(LoadFileTextCallback *)(std));)
Package( SetSaveFileTextCallback__,SetSaveFileTextCallback( *(SaveFileTextCallback *)(std));)
Package( LoadFileData__,*(unsigned char **)(std) = LoadFileData( *(const char **)(std), *(int **)(std + sizeof(const char *)));std += sizeof(unsigned char *);)
Package( UnloadFileData__,UnloadFileData( *(unsigned char **)(std));)
Package( SaveFileData__,*(bool*)(std) = SaveFileData( *(const char **)(std), *(void **)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(void *)));std += sizeof(bool);)
Package( ExportDataAsCode__,*(bool*)(std) = ExportDataAsCode( *(const unsigned char **)(std), *(int *)(std + sizeof(const unsigned char *)), *(const char **)(std + sizeof(const unsigned char *) + sizeof(int )));std += sizeof(bool);)
Package( LoadFileText__,*(char **)(std) = LoadFileText( *(const char **)(std));std += sizeof(char *);)
Package( UnloadFileText__,UnloadFileText( *(char **)(std));)
Package( SaveFileText__,*(bool*)(std) = SaveFileText( *(const char **)(std), *(char **)(std + sizeof(const char *)));std += sizeof(bool);)
Package( FileExists__,*(bool*)(std) = FileExists( *(const char **)(std));std += sizeof(bool);)
Package( DirectoryExists__,*(bool*)(std) = DirectoryExists( *(const char **)(std));std += sizeof(bool);)
Package( IsFileExtension__,*(bool*)(std) = IsFileExtension( *(const char **)(std), *(const char **)(std + sizeof(const char *)));std += sizeof(bool);)
Package( GetFileLength__,*(int*)(std) = GetFileLength( *(const char **)(std));std += sizeof(int);)
Package( GetFileExtension__,*(const char **)(std) = GetFileExtension( *(const char **)(std));std += sizeof(const char *);)
Package( GetFileName__,*(const char **)(std) = GetFileName( *(const char **)(std));std += sizeof(const char *);)
Package( GetFileNameWithoutExt__,*(const char **)(std) = GetFileNameWithoutExt( *(const char **)(std));std += sizeof(const char *);)
Package( GetDirectoryPath__,*(const char **)(std) = GetDirectoryPath( *(const char **)(std));std += sizeof(const char *);)
Package( GetPrevDirectoryPath__,*(const char **)(std) = GetPrevDirectoryPath( *(const char **)(std));std += sizeof(const char *);)
Package( GetWorkingDirectory__,*(const char **)(std) = GetWorkingDirectory();std += sizeof(const char *);)
Package( GetApplicationDirectory__,*(const char **)(std) = GetApplicationDirectory();std += sizeof(const char *);)
Package( MakeDirectory__,*(int*)(std) = MakeDirectory( *(const char **)(std));std += sizeof(int);)
Package( ChangeDirectory__,*(bool*)(std) = ChangeDirectory( *(const char **)(std));std += sizeof(bool);)
Package( IsPathFile__,*(bool*)(std) = IsPathFile( *(const char **)(std));std += sizeof(bool);)
Package( IsFileNameValid__,*(bool*)(std) = IsFileNameValid( *(const char **)(std));std += sizeof(bool);)
Package( LoadDirectoryFiles__,*(FilePathList*)(std) = LoadDirectoryFiles( *(const char **)(std));std += sizeof(FilePathList);)
Package( LoadDirectoryFilesEx__,*(FilePathList*)(std) = LoadDirectoryFilesEx( *(const char **)(std), *(const char **)(std + sizeof(const char *)), *(bool *)(std + sizeof(const char *) + sizeof(const char *)));std += sizeof(FilePathList);)
Package( UnloadDirectoryFiles__,UnloadDirectoryFiles( *(FilePathList *)(std));)
Package( IsFileDropped__,*(bool*)(std) = IsFileDropped();std += sizeof(bool);)
Package( LoadDroppedFiles__,*(FilePathList*)(std) = LoadDroppedFiles();std += sizeof(FilePathList);)
Package( UnloadDroppedFiles__,UnloadDroppedFiles( *(FilePathList *)(std));)
Package( GetFileModTime__,*(long*)(std) = GetFileModTime( *(const char **)(std));std += sizeof(long);)
Package( CompressData__,*(unsigned char **)(std) = CompressData( *(const unsigned char **)(std), *(int *)(std + sizeof(const unsigned char *)), *(int **)(std + sizeof(const unsigned char *) + sizeof(int )));std += sizeof(unsigned char *);)
Package( DecompressData__,*(unsigned char **)(std) = DecompressData( *(const unsigned char **)(std), *(int *)(std + sizeof(const unsigned char *)), *(int **)(std + sizeof(const unsigned char *) + sizeof(int )));std += sizeof(unsigned char *);)
Package( EncodeDataBase64__,*(char **)(std) = EncodeDataBase64( *(const unsigned char **)(std), *(int *)(std + sizeof(const unsigned char *)), *(int **)(std + sizeof(const unsigned char *) + sizeof(int )));std += sizeof(char *);)
Package( DecodeDataBase64__,*(unsigned char **)(std) = DecodeDataBase64( *(const unsigned char **)(std), *(int **)(std + sizeof(const unsigned char *)));std += sizeof(unsigned char *);)
Package( ComputeCRC32__,*(unsigned int*)(std) = ComputeCRC32( *(unsigned char **)(std), *(int *)(std + sizeof(unsigned char *)));std += sizeof(unsigned int);)
Package( ComputeMD5__,*(unsigned int **)(std) = ComputeMD5( *(unsigned char **)(std), *(int *)(std + sizeof(unsigned char *)));std += sizeof(unsigned int *);)
Package( ComputeSHA1__,*(unsigned int **)(std) = ComputeSHA1( *(unsigned char **)(std), *(int *)(std + sizeof(unsigned char *)));std += sizeof(unsigned int *);)
Package( LoadAutomationEventList__,*(AutomationEventList*)(std) = LoadAutomationEventList( *(const char **)(std));std += sizeof(AutomationEventList);)
Package( UnloadAutomationEventList__,UnloadAutomationEventList( *(AutomationEventList *)(std));)
Package( ExportAutomationEventList__,*(bool*)(std) = ExportAutomationEventList( *(AutomationEventList *)(std), *(const char **)(std + sizeof(AutomationEventList )));std += sizeof(bool);)
Package( SetAutomationEventList__,SetAutomationEventList( *(AutomationEventList **)(std));)
Package( SetAutomationEventBaseFrame__,SetAutomationEventBaseFrame( *(int *)(std));)
Package( StartAutomationEventRecording__,StartAutomationEventRecording();)
Package( StopAutomationEventRecording__,StopAutomationEventRecording();)
Package( PlayAutomationEvent__,PlayAutomationEvent( *(AutomationEvent *)(std));)
Package( IsKeyPressed__,*(bool*)(std) = IsKeyPressed( *(int *)(std));std += sizeof(bool);)
Package( IsKeyPressedRepeat__,*(bool*)(std) = IsKeyPressedRepeat( *(int *)(std));std += sizeof(bool);)
Package( IsKeyDown__,*(bool*)(std) = IsKeyDown( *(int *)(std));std += sizeof(bool);)
Package( IsKeyReleased__,*(bool*)(std) = IsKeyReleased( *(int *)(std));std += sizeof(bool);)
Package( IsKeyUp__,*(bool*)(std) = IsKeyUp( *(int *)(std));std += sizeof(bool);)
Package( GetKeyPressed__,*(int*)(std) = GetKeyPressed();std += sizeof(int);)
Package( GetCharPressed__,*(int*)(std) = GetCharPressed();std += sizeof(int);)
Package( SetExitKey__,SetExitKey( *(int *)(std));)
Package( IsGamepadAvailable__,*(bool*)(std) = IsGamepadAvailable( *(int *)(std));std += sizeof(bool);)
Package( GetGamepadName__,*(const char **)(std) = GetGamepadName( *(int *)(std));std += sizeof(const char *);)
Package( IsGamepadButtonPressed__,*(bool*)(std) = IsGamepadButtonPressed( *(int *)(std), *(int *)(std + sizeof(int )));std += sizeof(bool);)
Package( IsGamepadButtonDown__,*(bool*)(std) = IsGamepadButtonDown( *(int *)(std), *(int *)(std + sizeof(int )));std += sizeof(bool);)
Package( IsGamepadButtonReleased__,*(bool*)(std) = IsGamepadButtonReleased( *(int *)(std), *(int *)(std + sizeof(int )));std += sizeof(bool);)
Package( IsGamepadButtonUp__,*(bool*)(std) = IsGamepadButtonUp( *(int *)(std), *(int *)(std + sizeof(int )));std += sizeof(bool);)
Package( GetGamepadButtonPressed__,*(int*)(std) = GetGamepadButtonPressed();std += sizeof(int);)
Package( GetGamepadAxisCount__,*(int*)(std) = GetGamepadAxisCount( *(int *)(std));std += sizeof(int);)
Package( GetGamepadAxisMovement__,*(float*)(std) = GetGamepadAxisMovement( *(int *)(std), *(int *)(std + sizeof(int )));std += sizeof(float);)
Package( SetGamepadMappings__,*(int*)(std) = SetGamepadMappings( *(const char **)(std));std += sizeof(int);)
Package( SetGamepadVibration__,SetGamepadVibration( *(int *)(std), *(float *)(std + sizeof(int )), *(float *)(std + sizeof(int ) + sizeof(float )), *(float *)(std + sizeof(int ) + sizeof(float ) + sizeof(float )));)
Package( IsMouseButtonPressed__,*(bool*)(std) = IsMouseButtonPressed( *(int *)(std));std += sizeof(bool);)
Package( IsMouseButtonDown__,*(bool*)(std) = IsMouseButtonDown( *(int *)(std));std += sizeof(bool);)
Package( IsMouseButtonReleased__,*(bool*)(std) = IsMouseButtonReleased( *(int *)(std));std += sizeof(bool);)
Package( IsMouseButtonUp__,*(bool*)(std) = IsMouseButtonUp( *(int *)(std));std += sizeof(bool);)
Package( GetMouseX__,*(int*)(std) = GetMouseX();std += sizeof(int);)
Package( GetMouseY__,*(int*)(std) = GetMouseY();std += sizeof(int);)
Package( GetMousePosition__,*(Vector2*)(std) = GetMousePosition();std += sizeof(Vector2);)
Package( GetMouseDelta__,*(Vector2*)(std) = GetMouseDelta();std += sizeof(Vector2);)
Package( SetMousePosition__,SetMousePosition( *(int *)(std), *(int *)(std + sizeof(int )));)
Package( SetMouseOffset__,SetMouseOffset( *(int *)(std), *(int *)(std + sizeof(int )));)
Package( SetMouseScale__,SetMouseScale( *(float *)(std), *(float *)(std + sizeof(float )));)
Package( GetMouseWheelMove__,*(float*)(std) = GetMouseWheelMove();std += sizeof(float);)
Package( GetMouseWheelMoveV__,*(Vector2*)(std) = GetMouseWheelMoveV();std += sizeof(Vector2);)
Package( SetMouseCursor__,SetMouseCursor( *(int *)(std));)
Package( GetTouchX__,*(int*)(std) = GetTouchX();std += sizeof(int);)
Package( GetTouchY__,*(int*)(std) = GetTouchY();std += sizeof(int);)
Package( GetTouchPosition__,*(Vector2*)(std) = GetTouchPosition( *(int *)(std));std += sizeof(Vector2);)
Package( GetTouchPointId__,*(int*)(std) = GetTouchPointId( *(int *)(std));std += sizeof(int);)
Package( GetTouchPointCount__,*(int*)(std) = GetTouchPointCount();std += sizeof(int);)
Package( SetGesturesEnabled__,SetGesturesEnabled( *(unsigned int *)(std));)
Package( IsGestureDetected__,*(bool*)(std) = IsGestureDetected( *(unsigned int *)(std));std += sizeof(bool);)
Package( GetGestureDetected__,*(int*)(std) = GetGestureDetected();std += sizeof(int);)
Package( GetGestureHoldDuration__,*(float*)(std) = GetGestureHoldDuration();std += sizeof(float);)
Package( GetGestureDragVector__,*(Vector2*)(std) = GetGestureDragVector();std += sizeof(Vector2);)
Package( GetGestureDragAngle__,*(float*)(std) = GetGestureDragAngle();std += sizeof(float);)
Package( GetGesturePinchVector__,*(Vector2*)(std) = GetGesturePinchVector();std += sizeof(Vector2);)
Package( GetGesturePinchAngle__,*(float*)(std) = GetGesturePinchAngle();std += sizeof(float);)
Package( UpdateCamera__,UpdateCamera( *(Camera **)(std), *(int *)(std + sizeof(Camera *)));)
Package( UpdateCameraPro__,UpdateCameraPro( *(Camera **)(std), *(Vector3 *)(std + sizeof(Camera *)), *(Vector3 *)(std + sizeof(Camera *) + sizeof(Vector3 )), *(float *)(std + sizeof(Camera *) + sizeof(Vector3 ) + sizeof(Vector3 )));)
Package( SetShapesTexture__,SetShapesTexture( *(Texture2D *)(std), *(Rectangle *)(std + sizeof(Texture2D )));)
Package( GetShapesTexture__,*(Texture2D*)(std) = GetShapesTexture();std += sizeof(Texture2D);)
Package( GetShapesTextureRectangle__,*(Rectangle*)(std) = GetShapesTextureRectangle();std += sizeof(Rectangle);)
Package( DrawPixel__,DrawPixel( *(int *)(std), *(int *)(std + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int )));)
Package( DrawPixelV__,DrawPixelV( *(Vector2 *)(std), *(Color *)(std + sizeof(Vector2 )));)
Package( DrawLine__,DrawLine( *(int *)(std), *(int *)(std + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int )));)
Package( DrawLineV__,DrawLineV( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(Vector2 )));)
Package( DrawLineEx__,DrawLineEx( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(float )));)
Package( DrawLineStrip__,DrawLineStrip( *(const Vector2 **)(std), *(int *)(std + sizeof(const Vector2 *)), *(Color *)(std + sizeof(const Vector2 *) + sizeof(int )));)
Package( DrawLineBezier__,DrawLineBezier( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(float )));)
Package( DrawCircle__,DrawCircle( *(int *)(std), *(int *)(std + sizeof(int )), *(float *)(std + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(float )));)
Package( DrawCircleSector__,DrawCircleSector( *(Vector2 *)(std), *(float *)(std + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(float )), *(float *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float )), *(int *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float ) + sizeof(float )), *(Color *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float ) + sizeof(float ) + sizeof(int )));)
Package( DrawCircleSectorLines__,DrawCircleSectorLines( *(Vector2 *)(std), *(float *)(std + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(float )), *(float *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float )), *(int *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float ) + sizeof(float )), *(Color *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float ) + sizeof(float ) + sizeof(int )));)
Package( DrawCircleGradient__,DrawCircleGradient( *(int *)(std), *(int *)(std + sizeof(int )), *(float *)(std + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(float )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(float ) + sizeof(Color )));)
Package( DrawCircleV__,DrawCircleV( *(Vector2 *)(std), *(float *)(std + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(float )));)
Package( DrawCircleLines__,DrawCircleLines( *(int *)(std), *(int *)(std + sizeof(int )), *(float *)(std + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(float )));)
Package( DrawCircleLinesV__,DrawCircleLinesV( *(Vector2 *)(std), *(float *)(std + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(float )));)
Package( DrawEllipse__,DrawEllipse( *(int *)(std), *(int *)(std + sizeof(int )), *(float *)(std + sizeof(int ) + sizeof(int )), *(float *)(std + sizeof(int ) + sizeof(int ) + sizeof(float )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(float ) + sizeof(float )));)
Package( DrawEllipseLines__,DrawEllipseLines( *(int *)(std), *(int *)(std + sizeof(int )), *(float *)(std + sizeof(int ) + sizeof(int )), *(float *)(std + sizeof(int ) + sizeof(int ) + sizeof(float )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(float ) + sizeof(float )));)
Package( DrawRing__,DrawRing( *(Vector2 *)(std), *(float *)(std + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(float )), *(float *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float )), *(float *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float ) + sizeof(float )), *(int *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float ) + sizeof(float ) + sizeof(float )), *(Color *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float ) + sizeof(float ) + sizeof(float ) + sizeof(int )));)
Package( DrawRingLines__,DrawRingLines( *(Vector2 *)(std), *(float *)(std + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(float )), *(float *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float )), *(float *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float ) + sizeof(float )), *(int *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float ) + sizeof(float ) + sizeof(float )), *(Color *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(float ) + sizeof(float ) + sizeof(float ) + sizeof(int )));)
Package( DrawRectangle__,DrawRectangle( *(int *)(std), *(int *)(std + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int )));)
Package( DrawRectangleV__,DrawRectangleV( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(Vector2 )));)
Package( DrawRectangleRec__,DrawRectangleRec( *(Rectangle *)(std), *(Color *)(std + sizeof(Rectangle )));)
Package( DrawRectanglePro__,DrawRectanglePro( *(Rectangle *)(std), *(Vector2 *)(std + sizeof(Rectangle )), *(float *)(std + sizeof(Rectangle ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Rectangle ) + sizeof(Vector2 ) + sizeof(float )));)
Package( DrawRectangleGradientV__,DrawRectangleGradientV( *(int *)(std), *(int *)(std + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(Color )));)
Package( DrawRectangleGradientH__,DrawRectangleGradientH( *(int *)(std), *(int *)(std + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(Color )));)
Package( DrawRectangleGradientEx__,DrawRectangleGradientEx( *(Rectangle *)(std), *(Color *)(std + sizeof(Rectangle )), *(Color *)(std + sizeof(Rectangle ) + sizeof(Color )), *(Color *)(std + sizeof(Rectangle ) + sizeof(Color ) + sizeof(Color )), *(Color *)(std + sizeof(Rectangle ) + sizeof(Color ) + sizeof(Color ) + sizeof(Color )));)
Package( DrawRectangleLines__,DrawRectangleLines( *(int *)(std), *(int *)(std + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int )));)
Package( DrawRectangleLinesEx__,DrawRectangleLinesEx( *(Rectangle *)(std), *(float *)(std + sizeof(Rectangle )), *(Color *)(std + sizeof(Rectangle ) + sizeof(float )));)
Package( DrawRectangleRounded__,DrawRectangleRounded( *(Rectangle *)(std), *(float *)(std + sizeof(Rectangle )), *(int *)(std + sizeof(Rectangle ) + sizeof(float )), *(Color *)(std + sizeof(Rectangle ) + sizeof(float ) + sizeof(int )));)
Package( DrawRectangleRoundedLines__,DrawRectangleRoundedLines( *(Rectangle *)(std), *(float *)(std + sizeof(Rectangle )), *(int *)(std + sizeof(Rectangle ) + sizeof(float )), *(Color *)(std + sizeof(Rectangle ) + sizeof(float ) + sizeof(int )));)
Package( DrawRectangleRoundedLinesEx__,DrawRectangleRoundedLinesEx( *(Rectangle *)(std), *(float *)(std + sizeof(Rectangle )), *(int *)(std + sizeof(Rectangle ) + sizeof(float )), *(float *)(std + sizeof(Rectangle ) + sizeof(float ) + sizeof(int )), *(Color *)(std + sizeof(Rectangle ) + sizeof(float ) + sizeof(int ) + sizeof(float )));)
Package( DrawTriangle__,DrawTriangle( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )));)
Package( DrawTriangleLines__,DrawTriangleLines( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )));)
Package( DrawTriangleFan__,DrawTriangleFan( *(const Vector2 **)(std), *(int *)(std + sizeof(const Vector2 *)), *(Color *)(std + sizeof(const Vector2 *) + sizeof(int )));)
Package( DrawTriangleStrip__,DrawTriangleStrip( *(const Vector2 **)(std), *(int *)(std + sizeof(const Vector2 *)), *(Color *)(std + sizeof(const Vector2 *) + sizeof(int )));)
Package( DrawPoly__,DrawPoly( *(Vector2 *)(std), *(int *)(std + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(int )), *(float *)(std + sizeof(Vector2 ) + sizeof(int ) + sizeof(float )), *(Color *)(std + sizeof(Vector2 ) + sizeof(int ) + sizeof(float ) + sizeof(float )));)
Package( DrawPolyLines__,DrawPolyLines( *(Vector2 *)(std), *(int *)(std + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(int )), *(float *)(std + sizeof(Vector2 ) + sizeof(int ) + sizeof(float )), *(Color *)(std + sizeof(Vector2 ) + sizeof(int ) + sizeof(float ) + sizeof(float )));)
Package( DrawPolyLinesEx__,DrawPolyLinesEx( *(Vector2 *)(std), *(int *)(std + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(int )), *(float *)(std + sizeof(Vector2 ) + sizeof(int ) + sizeof(float )), *(float *)(std + sizeof(Vector2 ) + sizeof(int ) + sizeof(float ) + sizeof(float )), *(Color *)(std + sizeof(Vector2 ) + sizeof(int ) + sizeof(float ) + sizeof(float ) + sizeof(float )));)
Package( DrawSplineLinear__,DrawSplineLinear( *(const Vector2 **)(std), *(int *)(std + sizeof(const Vector2 *)), *(float *)(std + sizeof(const Vector2 *) + sizeof(int )), *(Color *)(std + sizeof(const Vector2 *) + sizeof(int ) + sizeof(float )));)
Package( DrawSplineBasis__,DrawSplineBasis( *(const Vector2 **)(std), *(int *)(std + sizeof(const Vector2 *)), *(float *)(std + sizeof(const Vector2 *) + sizeof(int )), *(Color *)(std + sizeof(const Vector2 *) + sizeof(int ) + sizeof(float )));)
Package( DrawSplineCatmullRom__,DrawSplineCatmullRom( *(const Vector2 **)(std), *(int *)(std + sizeof(const Vector2 *)), *(float *)(std + sizeof(const Vector2 *) + sizeof(int )), *(Color *)(std + sizeof(const Vector2 *) + sizeof(int ) + sizeof(float )));)
Package( DrawSplineBezierQuadratic__,DrawSplineBezierQuadratic( *(const Vector2 **)(std), *(int *)(std + sizeof(const Vector2 *)), *(float *)(std + sizeof(const Vector2 *) + sizeof(int )), *(Color *)(std + sizeof(const Vector2 *) + sizeof(int ) + sizeof(float )));)
Package( DrawSplineBezierCubic__,DrawSplineBezierCubic( *(const Vector2 **)(std), *(int *)(std + sizeof(const Vector2 *)), *(float *)(std + sizeof(const Vector2 *) + sizeof(int )), *(Color *)(std + sizeof(const Vector2 *) + sizeof(int ) + sizeof(float )));)
Package( DrawSplineSegmentLinear__,DrawSplineSegmentLinear( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(float )));)
Package( DrawSplineSegmentBasis__,DrawSplineSegmentBasis( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(float )));)
Package( DrawSplineSegmentCatmullRom__,DrawSplineSegmentCatmullRom( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(float )));)
Package( DrawSplineSegmentBezierQuadratic__,DrawSplineSegmentBezierQuadratic( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(float )));)
Package( DrawSplineSegmentBezierCubic__,DrawSplineSegmentBezierCubic( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(float )));)
Package( GetSplinePointLinear__,*(Vector2*)(std) = GetSplinePointLinear( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 )));std += sizeof(Vector2);)
Package( GetSplinePointBasis__,*(Vector2*)(std) = GetSplinePointBasis( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )));std += sizeof(Vector2);)
Package( GetSplinePointCatmullRom__,*(Vector2*)(std) = GetSplinePointCatmullRom( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )));std += sizeof(Vector2);)
Package( GetSplinePointBezierQuad__,*(Vector2*)(std) = GetSplinePointBezierQuad( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )));std += sizeof(Vector2);)
Package( GetSplinePointBezierCubic__,*(Vector2*)(std) = GetSplinePointBezierCubic( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )));std += sizeof(Vector2);)
Package( CheckCollisionRecs__,*(bool*)(std) = CheckCollisionRecs( *(Rectangle *)(std), *(Rectangle *)(std + sizeof(Rectangle )));std += sizeof(bool);)
Package( CheckCollisionCircles__,*(bool*)(std) = CheckCollisionCircles( *(Vector2 *)(std), *(float *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(float )), *(float *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(Vector2 )));std += sizeof(bool);)
Package( CheckCollisionCircleRec__,*(bool*)(std) = CheckCollisionCircleRec( *(Vector2 *)(std), *(float *)(std + sizeof(Vector2 )), *(Rectangle *)(std + sizeof(Vector2 ) + sizeof(float )));std += sizeof(bool);)
Package( CheckCollisionCircleLine__,*(bool*)(std) = CheckCollisionCircleLine( *(Vector2 *)(std), *(float *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(float )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(float ) + sizeof(Vector2 )));std += sizeof(bool);)
Package( CheckCollisionPointRec__,*(bool*)(std) = CheckCollisionPointRec( *(Vector2 *)(std), *(Rectangle *)(std + sizeof(Vector2 )));std += sizeof(bool);)
Package( CheckCollisionPointCircle__,*(bool*)(std) = CheckCollisionPointCircle( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(float *)(std + sizeof(Vector2 ) + sizeof(Vector2 )));std += sizeof(bool);)
Package( CheckCollisionPointTriangle__,*(bool*)(std) = CheckCollisionPointTriangle( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )));std += sizeof(bool);)
Package( CheckCollisionPointLine__,*(bool*)(std) = CheckCollisionPointLine( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(int *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )));std += sizeof(bool);)
Package( CheckCollisionPointPoly__,*(bool*)(std) = CheckCollisionPointPoly( *(Vector2 *)(std), *(const Vector2 **)(std + sizeof(Vector2 )), *(int *)(std + sizeof(Vector2 ) + sizeof(const Vector2 *)));std += sizeof(bool);)
Package( CheckCollisionLines__,*(bool*)(std) = CheckCollisionLines( *(Vector2 *)(std), *(Vector2 *)(std + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(Vector2 **)(std + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )));std += sizeof(bool);)
Package( GetCollisionRec__,*(Rectangle*)(std) = GetCollisionRec( *(Rectangle *)(std), *(Rectangle *)(std + sizeof(Rectangle )));std += sizeof(Rectangle);)
Package( LoadImage__,*(Image*)(std) = LoadImage( *(const char **)(std));std += sizeof(Image);)
Package( LoadImageRaw__,*(Image*)(std) = LoadImageRaw( *(const char **)(std), *(int *)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(int )), *(int *)(std + sizeof(const char *) + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(const char *) + sizeof(int ) + sizeof(int ) + sizeof(int )));std += sizeof(Image);)
Package( LoadImageAnim__,*(Image*)(std) = LoadImageAnim( *(const char **)(std), *(int **)(std + sizeof(const char *)));std += sizeof(Image);)
Package( LoadImageAnimFromMemory__,*(Image*)(std) = LoadImageAnimFromMemory( *(const char **)(std), *(const unsigned char **)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(const unsigned char *)), *(int **)(std + sizeof(const char *) + sizeof(const unsigned char *) + sizeof(int )));std += sizeof(Image);)
Package( LoadImageFromMemory__,*(Image*)(std) = LoadImageFromMemory( *(const char **)(std), *(const unsigned char **)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(const unsigned char *)));std += sizeof(Image);)
Package( LoadImageFromTexture__,*(Image*)(std) = LoadImageFromTexture( *(Texture2D *)(std));std += sizeof(Image);)
Package( LoadImageFromScreen__,*(Image*)(std) = LoadImageFromScreen();std += sizeof(Image);)
Package( IsImageValid__,*(bool*)(std) = IsImageValid( *(Image *)(std));std += sizeof(bool);)
Package( UnloadImage__,UnloadImage( *(Image *)(std));)
Package( ExportImage__,*(bool*)(std) = ExportImage( *(Image *)(std), *(const char **)(std + sizeof(Image )));std += sizeof(bool);)
Package( ExportImageToMemory__,*(unsigned char **)(std) = ExportImageToMemory( *(Image *)(std), *(const char **)(std + sizeof(Image )), *(int **)(std + sizeof(Image ) + sizeof(const char *)));std += sizeof(unsigned char *);)
Package( ExportImageAsCode__,*(bool*)(std) = ExportImageAsCode( *(Image *)(std), *(const char **)(std + sizeof(Image )));std += sizeof(bool);)
Package( GenImageColor__,*(Image*)(std) = GenImageColor( *(int *)(std), *(int *)(std + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int )));std += sizeof(Image);)
Package( GenImageGradientLinear__,*(Image*)(std) = GenImageGradientLinear( *(int *)(std), *(int *)(std + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(Color )));std += sizeof(Image);)
Package( GenImageGradientRadial__,*(Image*)(std) = GenImageGradientRadial( *(int *)(std), *(int *)(std + sizeof(int )), *(float *)(std + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(float )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(float ) + sizeof(Color )));std += sizeof(Image);)
Package( GenImageGradientSquare__,*(Image*)(std) = GenImageGradientSquare( *(int *)(std), *(int *)(std + sizeof(int )), *(float *)(std + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(float )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(float ) + sizeof(Color )));std += sizeof(Image);)
Package( GenImageChecked__,*(Image*)(std) = GenImageChecked( *(int *)(std), *(int *)(std + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(Color )));std += sizeof(Image);)
Package( GenImageWhiteNoise__,*(Image*)(std) = GenImageWhiteNoise( *(int *)(std), *(int *)(std + sizeof(int )), *(float *)(std + sizeof(int ) + sizeof(int )));std += sizeof(Image);)
Package( GenImagePerlinNoise__,*(Image*)(std) = GenImagePerlinNoise( *(int *)(std), *(int *)(std + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int ) + sizeof(int )), *(float *)(std + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int )));std += sizeof(Image);)
Package( GenImageCellular__,*(Image*)(std) = GenImageCellular( *(int *)(std), *(int *)(std + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int )));std += sizeof(Image);)
Package( GenImageText__,*(Image*)(std) = GenImageText( *(int *)(std), *(int *)(std + sizeof(int )), *(const char **)(std + sizeof(int ) + sizeof(int )));std += sizeof(Image);)
Package( ImageCopy__,*(Image*)(std) = ImageCopy( *(Image *)(std));std += sizeof(Image);)
Package( ImageFromImage__,*(Image*)(std) = ImageFromImage( *(Image *)(std), *(Rectangle *)(std + sizeof(Image )));std += sizeof(Image);)
Package( ImageFromChannel__,*(Image*)(std) = ImageFromChannel( *(Image *)(std), *(int *)(std + sizeof(Image )));std += sizeof(Image);)
Package( ImageText__,*(Image*)(std) = ImageText( *(const char **)(std), *(int *)(std + sizeof(const char *)), *(Color *)(std + sizeof(const char *) + sizeof(int )));std += sizeof(Image);)
Package( ImageTextEx__,*(Image*)(std) = ImageTextEx( *(Font *)(std), *(const char **)(std + sizeof(Font )), *(float *)(std + sizeof(Font ) + sizeof(const char *)), *(float *)(std + sizeof(Font ) + sizeof(const char *) + sizeof(float )), *(Color *)(std + sizeof(Font ) + sizeof(const char *) + sizeof(float ) + sizeof(float )));std += sizeof(Image);)
Package( ImageFormat__,ImageFormat( *(Image **)(std), *(int *)(std + sizeof(Image *)));)
Package( ImageToPOT__,ImageToPOT( *(Image **)(std), *(Color *)(std + sizeof(Image *)));)
Package( ImageCrop__,ImageCrop( *(Image **)(std), *(Rectangle *)(std + sizeof(Image *)));)
Package( ImageAlphaCrop__,ImageAlphaCrop( *(Image **)(std), *(float *)(std + sizeof(Image *)));)
Package( ImageAlphaClear__,ImageAlphaClear( *(Image **)(std), *(Color *)(std + sizeof(Image *)), *(float *)(std + sizeof(Image *) + sizeof(Color )));)
Package( ImageAlphaMask__,ImageAlphaMask( *(Image **)(std), *(Image *)(std + sizeof(Image *)));)
Package( ImageAlphaPremultiply__,ImageAlphaPremultiply( *(Image **)(std));)
Package( ImageBlurGaussian__,ImageBlurGaussian( *(Image **)(std), *(int *)(std + sizeof(Image *)));)
Package( ImageKernelConvolution__,ImageKernelConvolution( *(Image **)(std), *(const float **)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(const float *)));)
Package( ImageResize__,ImageResize( *(Image **)(std), *(int *)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(int )));)
Package( ImageResizeNN__,ImageResizeNN( *(Image **)(std), *(int *)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(int )));)
Package( ImageResizeCanvas__,ImageResizeCanvas( *(Image **)(std), *(int *)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(int )), *(int *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int )));)
Package( ImageMipmaps__,ImageMipmaps( *(Image **)(std));)
Package( ImageDither__,ImageDither( *(Image **)(std), *(int *)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(int )), *(int *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int ) + sizeof(int )));)
Package( ImageFlipVertical__,ImageFlipVertical( *(Image **)(std));)
Package( ImageFlipHorizontal__,ImageFlipHorizontal( *(Image **)(std));)
Package( ImageRotate__,ImageRotate( *(Image **)(std), *(int *)(std + sizeof(Image *)));)
Package( ImageRotateCW__,ImageRotateCW( *(Image **)(std));)
Package( ImageRotateCCW__,ImageRotateCCW( *(Image **)(std));)
Package( ImageColorTint__,ImageColorTint( *(Image **)(std), *(Color *)(std + sizeof(Image *)));)
Package( ImageColorInvert__,ImageColorInvert( *(Image **)(std));)
Package( ImageColorGrayscale__,ImageColorGrayscale( *(Image **)(std));)
Package( ImageColorContrast__,ImageColorContrast( *(Image **)(std), *(float *)(std + sizeof(Image *)));)
Package( ImageColorBrightness__,ImageColorBrightness( *(Image **)(std), *(int *)(std + sizeof(Image *)));)
Package( ImageColorReplace__,ImageColorReplace( *(Image **)(std), *(Color *)(std + sizeof(Image *)), *(Color *)(std + sizeof(Image *) + sizeof(Color )));)
Package( LoadImageColors__,*(Color **)(std) = LoadImageColors( *(Image *)(std));std += sizeof(Color *);)
Package( LoadImagePalette__,*(Color **)(std) = LoadImagePalette( *(Image *)(std), *(int *)(std + sizeof(Image )), *(int **)(std + sizeof(Image ) + sizeof(int )));std += sizeof(Color *);)
Package( UnloadImageColors__,UnloadImageColors( *(Color **)(std));)
Package( UnloadImagePalette__,UnloadImagePalette( *(Color **)(std));)
Package( GetImageAlphaBorder__,*(Rectangle*)(std) = GetImageAlphaBorder( *(Image *)(std), *(float *)(std + sizeof(Image )));std += sizeof(Rectangle);)
Package( GetImageColor__,*(Color*)(std) = GetImageColor( *(Image *)(std), *(int *)(std + sizeof(Image )), *(int *)(std + sizeof(Image ) + sizeof(int )));std += sizeof(Color);)
Package( ImageClearBackground__,ImageClearBackground( *(Image **)(std), *(Color *)(std + sizeof(Image *)));)
Package( ImageDrawPixel__,ImageDrawPixel( *(Image **)(std), *(int *)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(int )), *(Color *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int )));)
Package( ImageDrawPixelV__,ImageDrawPixelV( *(Image **)(std), *(Vector2 *)(std + sizeof(Image *)), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 )));)
Package( ImageDrawLine__,ImageDrawLine( *(Image **)(std), *(int *)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(int )), *(int *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int )));)
Package( ImageDrawLineV__,ImageDrawLineV( *(Image **)(std), *(Vector2 *)(std + sizeof(Image *)), *(Vector2 *)(std + sizeof(Image *) + sizeof(Vector2 )), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(Vector2 )));)
Package( ImageDrawLineEx__,ImageDrawLineEx( *(Image **)(std), *(Vector2 *)(std + sizeof(Image *)), *(Vector2 *)(std + sizeof(Image *) + sizeof(Vector2 )), *(int *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(int )));)
Package( ImageDrawCircle__,ImageDrawCircle( *(Image **)(std), *(int *)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(int )), *(int *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int ) + sizeof(int )));)
Package( ImageDrawCircleV__,ImageDrawCircleV( *(Image **)(std), *(Vector2 *)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(Vector2 )), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(int )));)
Package( ImageDrawCircleLines__,ImageDrawCircleLines( *(Image **)(std), *(int *)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(int )), *(int *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int ) + sizeof(int )));)
Package( ImageDrawCircleLinesV__,ImageDrawCircleLinesV( *(Image **)(std), *(Vector2 *)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(Vector2 )), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(int )));)
Package( ImageDrawRectangle__,ImageDrawRectangle( *(Image **)(std), *(int *)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(int )), *(int *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(Image *) + sizeof(int ) + sizeof(int ) + sizeof(int ) + sizeof(int )));)
Package( ImageDrawRectangleV__,ImageDrawRectangleV( *(Image **)(std), *(Vector2 *)(std + sizeof(Image *)), *(Vector2 *)(std + sizeof(Image *) + sizeof(Vector2 )), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(Vector2 )));)
Package( ImageDrawRectangleRec__,ImageDrawRectangleRec( *(Image **)(std), *(Rectangle *)(std + sizeof(Image *)), *(Color *)(std + sizeof(Image *) + sizeof(Rectangle )));)
Package( ImageDrawRectangleLines__,ImageDrawRectangleLines( *(Image **)(std), *(Rectangle *)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(Rectangle )), *(Color *)(std + sizeof(Image *) + sizeof(Rectangle ) + sizeof(int )));)
Package( ImageDrawTriangle__,ImageDrawTriangle( *(Image **)(std), *(Vector2 *)(std + sizeof(Image *)), *(Vector2 *)(std + sizeof(Image *) + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )));)
Package( ImageDrawTriangleEx__,ImageDrawTriangleEx( *(Image **)(std), *(Vector2 *)(std + sizeof(Image *)), *(Vector2 *)(std + sizeof(Image *) + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Color )), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Color ) + sizeof(Color )));)
Package( ImageDrawTriangleLines__,ImageDrawTriangleLines( *(Image **)(std), *(Vector2 *)(std + sizeof(Image *)), *(Vector2 *)(std + sizeof(Image *) + sizeof(Vector2 )), *(Vector2 *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(Vector2 )));)
Package( ImageDrawTriangleFan__,ImageDrawTriangleFan( *(Image **)(std), *(Vector2 **)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(Vector2 *)), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 *) + sizeof(int )));)
Package( ImageDrawTriangleStrip__,ImageDrawTriangleStrip( *(Image **)(std), *(Vector2 **)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(Vector2 *)), *(Color *)(std + sizeof(Image *) + sizeof(Vector2 *) + sizeof(int )));)
Package( ImageDraw__,ImageDraw( *(Image **)(std), *(Image *)(std + sizeof(Image *)), *(Rectangle *)(std + sizeof(Image *) + sizeof(Image )), *(Rectangle *)(std + sizeof(Image *) + sizeof(Image ) + sizeof(Rectangle )), *(Color *)(std + sizeof(Image *) + sizeof(Image ) + sizeof(Rectangle ) + sizeof(Rectangle )));)
Package( ImageDrawText__,ImageDrawText( *(Image **)(std), *(const char **)(std + sizeof(Image *)), *(int *)(std + sizeof(Image *) + sizeof(const char *)), *(int *)(std + sizeof(Image *) + sizeof(const char *) + sizeof(int )), *(int *)(std + sizeof(Image *) + sizeof(const char *) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(Image *) + sizeof(const char *) + sizeof(int ) + sizeof(int ) + sizeof(int )));)
Package( ImageDrawTextEx__,ImageDrawTextEx( *(Image **)(std), *(Font *)(std + sizeof(Image *)), *(const char **)(std + sizeof(Image *) + sizeof(Font )), *(Vector2 *)(std + sizeof(Image *) + sizeof(Font ) + sizeof(const char *)), *(float *)(std + sizeof(Image *) + sizeof(Font ) + sizeof(const char *) + sizeof(Vector2 )), *(float *)(std + sizeof(Image *) + sizeof(Font ) + sizeof(const char *) + sizeof(Vector2 ) + sizeof(float )), *(Color *)(std + sizeof(Image *) + sizeof(Font ) + sizeof(const char *) + sizeof(Vector2 ) + sizeof(float ) + sizeof(float )));)
Package( LoadTexture__,*(Texture2D*)(std) = LoadTexture( *(const char **)(std));std += sizeof(Texture2D);)
Package( LoadTextureFromImage__,*(Texture2D*)(std) = LoadTextureFromImage( *(Image *)(std));std += sizeof(Texture2D);)
Package( LoadTextureCubemap__,*(TextureCubemap*)(std) = LoadTextureCubemap( *(Image *)(std), *(int *)(std + sizeof(Image )));std += sizeof(TextureCubemap);)
Package( LoadRenderTexture__,*(RenderTexture2D*)(std) = LoadRenderTexture( *(int *)(std), *(int *)(std + sizeof(int )));std += sizeof(RenderTexture2D);)
Package( IsTextureValid__,*(bool*)(std) = IsTextureValid( *(Texture2D *)(std));std += sizeof(bool);)
Package( UnloadTexture__,UnloadTexture( *(Texture2D *)(std));)
Package( IsRenderTextureValid__,*(bool*)(std) = IsRenderTextureValid( *(RenderTexture2D *)(std));std += sizeof(bool);)
Package( UnloadRenderTexture__,UnloadRenderTexture( *(RenderTexture2D *)(std));)
Package( UpdateTexture__,UpdateTexture( *(Texture2D *)(std), *(const void **)(std + sizeof(Texture2D )));)
Package( UpdateTextureRec__,UpdateTextureRec( *(Texture2D *)(std), *(Rectangle *)(std + sizeof(Texture2D )), *(const void **)(std + sizeof(Texture2D ) + sizeof(Rectangle )));)
Package( GenTextureMipmaps__,GenTextureMipmaps( *(Texture2D **)(std));)
Package( SetTextureFilter__,SetTextureFilter( *(Texture2D *)(std), *(int *)(std + sizeof(Texture2D )));)
Package( SetTextureWrap__,SetTextureWrap( *(Texture2D *)(std), *(int *)(std + sizeof(Texture2D )));)
Package( DrawTexture__,DrawTexture( *(Texture2D *)(std), *(int *)(std + sizeof(Texture2D )), *(int *)(std + sizeof(Texture2D ) + sizeof(int )), *(Color *)(std + sizeof(Texture2D ) + sizeof(int ) + sizeof(int )));)
Package( DrawTextureV__,DrawTextureV( *(Texture2D *)(std), *(Vector2 *)(std + sizeof(Texture2D )), *(Color *)(std + sizeof(Texture2D ) + sizeof(Vector2 )));)
Package( DrawTextureEx__,DrawTextureEx( *(Texture2D *)(std), *(Vector2 *)(std + sizeof(Texture2D )), *(float *)(std + sizeof(Texture2D ) + sizeof(Vector2 )), *(float *)(std + sizeof(Texture2D ) + sizeof(Vector2 ) + sizeof(float )), *(Color *)(std + sizeof(Texture2D ) + sizeof(Vector2 ) + sizeof(float ) + sizeof(float )));)
Package( DrawTextureRec__,DrawTextureRec( *(Texture2D *)(std), *(Rectangle *)(std + sizeof(Texture2D )), *(Vector2 *)(std + sizeof(Texture2D ) + sizeof(Rectangle )), *(Color *)(std + sizeof(Texture2D ) + sizeof(Rectangle ) + sizeof(Vector2 )));)
Package( DrawTexturePro__,DrawTexturePro( *(Texture2D *)(std), *(Rectangle *)(std + sizeof(Texture2D )), *(Rectangle *)(std + sizeof(Texture2D ) + sizeof(Rectangle )), *(Vector2 *)(std + sizeof(Texture2D ) + sizeof(Rectangle ) + sizeof(Rectangle )), *(float *)(std + sizeof(Texture2D ) + sizeof(Rectangle ) + sizeof(Rectangle ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Texture2D ) + sizeof(Rectangle ) + sizeof(Rectangle ) + sizeof(Vector2 ) + sizeof(float )));)
Package( DrawTextureNPatch__,DrawTextureNPatch( *(Texture2D *)(std), *(NPatchInfo *)(std + sizeof(Texture2D )), *(Rectangle *)(std + sizeof(Texture2D ) + sizeof(NPatchInfo )), *(Vector2 *)(std + sizeof(Texture2D ) + sizeof(NPatchInfo ) + sizeof(Rectangle )), *(float *)(std + sizeof(Texture2D ) + sizeof(NPatchInfo ) + sizeof(Rectangle ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Texture2D ) + sizeof(NPatchInfo ) + sizeof(Rectangle ) + sizeof(Vector2 ) + sizeof(float )));)
Package( ColorIsEqual__,*(bool*)(std) = ColorIsEqual( *(Color *)(std), *(Color *)(std + sizeof(Color )));std += sizeof(bool);)
Package( Fade__,*(Color*)(std) = Fade( *(Color *)(std), *(float *)(std + sizeof(Color )));std += sizeof(Color);)
Package( ColorToInt__,*(int*)(std) = ColorToInt( *(Color *)(std));std += sizeof(int);)
Package( ColorNormalize__,*(Vector4*)(std) = ColorNormalize( *(Color *)(std));std += sizeof(Vector4);)
Package( ColorFromNormalized__,*(Color*)(std) = ColorFromNormalized( *(Vector4 *)(std));std += sizeof(Color);)
Package( ColorToHSV__,*(Vector3*)(std) = ColorToHSV( *(Color *)(std));std += sizeof(Vector3);)
Package( ColorFromHSV__,*(Color*)(std) = ColorFromHSV( *(float *)(std), *(float *)(std + sizeof(float )), *(float *)(std + sizeof(float ) + sizeof(float )));std += sizeof(Color);)
Package( ColorTint__,*(Color*)(std) = ColorTint( *(Color *)(std), *(Color *)(std + sizeof(Color )));std += sizeof(Color);)
Package( ColorBrightness__,*(Color*)(std) = ColorBrightness( *(Color *)(std), *(float *)(std + sizeof(Color )));std += sizeof(Color);)
Package( ColorContrast__,*(Color*)(std) = ColorContrast( *(Color *)(std), *(float *)(std + sizeof(Color )));std += sizeof(Color);)
Package( ColorAlpha__,*(Color*)(std) = ColorAlpha( *(Color *)(std), *(float *)(std + sizeof(Color )));std += sizeof(Color);)
Package( ColorAlphaBlend__,*(Color*)(std) = ColorAlphaBlend( *(Color *)(std), *(Color *)(std + sizeof(Color )), *(Color *)(std + sizeof(Color ) + sizeof(Color )));std += sizeof(Color);)
Package( ColorLerp__,*(Color*)(std) = ColorLerp( *(Color *)(std), *(Color *)(std + sizeof(Color )), *(float *)(std + sizeof(Color ) + sizeof(Color )));std += sizeof(Color);)
Package( GetColor__,*(Color*)(std) = GetColor( *(unsigned int *)(std));std += sizeof(Color);)
Package( GetPixelColor__,*(Color*)(std) = GetPixelColor( *(void **)(std), *(int *)(std + sizeof(void *)));std += sizeof(Color);)
Package( SetPixelColor__,SetPixelColor( *(void **)(std), *(Color *)(std + sizeof(void *)), *(int *)(std + sizeof(void *) + sizeof(Color )));)
Package( GetPixelDataSize__,*(int*)(std) = GetPixelDataSize( *(int *)(std), *(int *)(std + sizeof(int )), *(int *)(std + sizeof(int ) + sizeof(int )));std += sizeof(int);)
Package( GetFontDefault__,*(Font*)(std) = GetFontDefault();std += sizeof(Font);)
Package( LoadFont__,*(Font*)(std) = LoadFont( *(const char **)(std));std += sizeof(Font);)
Package( LoadFontEx__,*(Font*)(std) = LoadFontEx( *(const char **)(std), *(int *)(std + sizeof(const char *)), *(int **)(std + sizeof(const char *) + sizeof(int )), *(int *)(std + sizeof(const char *) + sizeof(int ) + sizeof(int *)));std += sizeof(Font);)
Package( LoadFontFromImage__,*(Font*)(std) = LoadFontFromImage( *(Image *)(std), *(Color *)(std + sizeof(Image )), *(int *)(std + sizeof(Image ) + sizeof(Color )));std += sizeof(Font);)
Package( LoadFontFromMemory__,*(Font*)(std) = LoadFontFromMemory( *(const char **)(std), *(const unsigned char **)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(const unsigned char *)), *(int *)(std + sizeof(const char *) + sizeof(const unsigned char *) + sizeof(int )), *(int **)(std + sizeof(const char *) + sizeof(const unsigned char *) + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(const char *) + sizeof(const unsigned char *) + sizeof(int ) + sizeof(int ) + sizeof(int *)));std += sizeof(Font);)
Package( IsFontValid__,*(bool*)(std) = IsFontValid( *(Font *)(std));std += sizeof(bool);)
Package( LoadFontData__,*(GlyphInfo **)(std) = LoadFontData( *(const unsigned char **)(std), *(int *)(std + sizeof(const unsigned char *)), *(int *)(std + sizeof(const unsigned char *) + sizeof(int )), *(int **)(std + sizeof(const unsigned char *) + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(const unsigned char *) + sizeof(int ) + sizeof(int ) + sizeof(int *)), *(int *)(std + sizeof(const unsigned char *) + sizeof(int ) + sizeof(int ) + sizeof(int *) + sizeof(int )));std += sizeof(GlyphInfo *);)
Package( GenImageFontAtlas__,*(Image*)(std) = GenImageFontAtlas( *(const GlyphInfo **)(std), *(Rectangle ***)(std + sizeof(const GlyphInfo *)), *(int *)(std + sizeof(const GlyphInfo *) + sizeof(Rectangle **)), *(int *)(std + sizeof(const GlyphInfo *) + sizeof(Rectangle **) + sizeof(int )), *(int *)(std + sizeof(const GlyphInfo *) + sizeof(Rectangle **) + sizeof(int ) + sizeof(int )), *(int *)(std + sizeof(const GlyphInfo *) + sizeof(Rectangle **) + sizeof(int ) + sizeof(int ) + sizeof(int )));std += sizeof(Image);)
Package( UnloadFontData__,UnloadFontData( *(GlyphInfo **)(std), *(int *)(std + sizeof(GlyphInfo *)));)
Package( UnloadFont__,UnloadFont( *(Font *)(std));)
Package( ExportFontAsCode__,*(bool*)(std) = ExportFontAsCode( *(Font *)(std), *(const char **)(std + sizeof(Font )));std += sizeof(bool);)
Package( DrawFPS__,DrawFPS( *(int *)(std), *(int *)(std + sizeof(int )));)
Package( DrawText__,DrawText( *(const char **)(std), *(int *)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(int )), *(int *)(std + sizeof(const char *) + sizeof(int ) + sizeof(int )), *(Color *)(std + sizeof(const char *) + sizeof(int ) + sizeof(int ) + sizeof(int )));)
Package( DrawTextEx__,DrawTextEx( *(Font *)(std), *(const char **)(std + sizeof(Font )), *(Vector2 *)(std + sizeof(Font ) + sizeof(const char *)), *(float *)(std + sizeof(Font ) + sizeof(const char *) + sizeof(Vector2 )), *(float *)(std + sizeof(Font ) + sizeof(const char *) + sizeof(Vector2 ) + sizeof(float )), *(Color *)(std + sizeof(Font ) + sizeof(const char *) + sizeof(Vector2 ) + sizeof(float ) + sizeof(float )));)
Package( DrawTextPro__,DrawTextPro( *(Font *)(std), *(const char **)(std + sizeof(Font )), *(Vector2 *)(std + sizeof(Font ) + sizeof(const char *)), *(Vector2 *)(std + sizeof(Font ) + sizeof(const char *) + sizeof(Vector2 )), *(float *)(std + sizeof(Font ) + sizeof(const char *) + sizeof(Vector2 ) + sizeof(Vector2 )), *(float *)(std + sizeof(Font ) + sizeof(const char *) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(float )), *(float *)(std + sizeof(Font ) + sizeof(const char *) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(float ) + sizeof(float )), *(Color *)(std + sizeof(Font ) + sizeof(const char *) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(float ) + sizeof(float ) + sizeof(float )));)
Package( DrawTextCodepoint__,DrawTextCodepoint( *(Font *)(std), *(int *)(std + sizeof(Font )), *(Vector2 *)(std + sizeof(Font ) + sizeof(int )), *(float *)(std + sizeof(Font ) + sizeof(int ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Font ) + sizeof(int ) + sizeof(Vector2 ) + sizeof(float )));)
Package( DrawTextCodepoints__,DrawTextCodepoints( *(Font *)(std), *(const int **)(std + sizeof(Font )), *(int *)(std + sizeof(Font ) + sizeof(const int *)), *(Vector2 *)(std + sizeof(Font ) + sizeof(const int *) + sizeof(int )), *(float *)(std + sizeof(Font ) + sizeof(const int *) + sizeof(int ) + sizeof(Vector2 )), *(float *)(std + sizeof(Font ) + sizeof(const int *) + sizeof(int ) + sizeof(Vector2 ) + sizeof(float )), *(Color *)(std + sizeof(Font ) + sizeof(const int *) + sizeof(int ) + sizeof(Vector2 ) + sizeof(float ) + sizeof(float )));)
Package( SetTextLineSpacing__,SetTextLineSpacing( *(int *)(std));)
Package( MeasureText__,*(int*)(std) = MeasureText( *(const char **)(std), *(int *)(std + sizeof(const char *)));std += sizeof(int);)
Package( MeasureTextEx__,*(Vector2*)(std) = MeasureTextEx( *(Font *)(std), *(const char **)(std + sizeof(Font )), *(float *)(std + sizeof(Font ) + sizeof(const char *)), *(float *)(std + sizeof(Font ) + sizeof(const char *) + sizeof(float )));std += sizeof(Vector2);)
Package( GetGlyphIndex__,*(int*)(std) = GetGlyphIndex( *(Font *)(std), *(int *)(std + sizeof(Font )));std += sizeof(int);)
Package( GetGlyphInfo__,*(GlyphInfo*)(std) = GetGlyphInfo( *(Font *)(std), *(int *)(std + sizeof(Font )));std += sizeof(GlyphInfo);)
Package( GetGlyphAtlasRec__,*(Rectangle*)(std) = GetGlyphAtlasRec( *(Font *)(std), *(int *)(std + sizeof(Font )));std += sizeof(Rectangle);)
Package( LoadUTF8__,*(char **)(std) = LoadUTF8( *(const int **)(std), *(int *)(std + sizeof(const int *)));std += sizeof(char *);)
Package( UnloadUTF8__,UnloadUTF8( *(char **)(std));)
Package( LoadCodepoints__,*(int **)(std) = LoadCodepoints( *(const char **)(std), *(int **)(std + sizeof(const char *)));std += sizeof(int *);)
Package( UnloadCodepoints__,UnloadCodepoints( *(int **)(std));)
Package( GetCodepointCount__,*(int*)(std) = GetCodepointCount( *(const char **)(std));std += sizeof(int);)
Package( GetCodepoint__,*(int*)(std) = GetCodepoint( *(const char **)(std), *(int **)(std + sizeof(const char *)));std += sizeof(int);)
Package( GetCodepointNext__,*(int*)(std) = GetCodepointNext( *(const char **)(std), *(int **)(std + sizeof(const char *)));std += sizeof(int);)
Package( GetCodepointPrevious__,*(int*)(std) = GetCodepointPrevious( *(const char **)(std), *(int **)(std + sizeof(const char *)));std += sizeof(int);)
Package( CodepointToUTF8__,*(const char **)(std) = CodepointToUTF8( *(int *)(std), *(int **)(std + sizeof(int )));std += sizeof(const char *);)
Package( TextCopy__,*(int*)(std) = TextCopy( *(char **)(std), *(const char **)(std + sizeof(char *)));std += sizeof(int);)
Package( TextIsEqual__,*(bool*)(std) = TextIsEqual( *(const char **)(std), *(const char **)(std + sizeof(const char *)));std += sizeof(bool);)
Package( TextLength__,*(unsigned int*)(std) = TextLength( *(const char **)(std));std += sizeof(unsigned int);)
Package( TextFormat__,*(const char **)(std) = TextFormat( *(const char **)(std), *(int *)(std + sizeof(const char *)));std += sizeof(const char *);)
Package( TextSubtext__,*(const char **)(std) = TextSubtext( *(const char **)(std), *(int *)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(int )));std += sizeof(const char *);)
Package( TextReplace__,*(char **)(std) = TextReplace( *(const char **)(std), *(const char **)(std + sizeof(const char *)), *(const char **)(std + sizeof(const char *) + sizeof(const char *)));std += sizeof(char *);)
Package( TextInsert__,*(char **)(std) = TextInsert( *(const char **)(std), *(const char **)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(const char *)));std += sizeof(char *);)
Package( TextJoin__,*(const char **)(std) = TextJoin( *(const char ***)(std), *(int *)(std + sizeof(const char **)), *(const char **)(std + sizeof(const char **) + sizeof(int )));std += sizeof(const char *);)
Package( TextSplit__,*(const char ***)(std) = TextSplit( *(const char **)(std), *(char *)(std + sizeof(const char *)), *(int **)(std + sizeof(const char *) + sizeof(char )));std += sizeof(const char **);)
Package( TextAppend__,TextAppend( *(char **)(std), *(const char **)(std + sizeof(char *)), *(int **)(std + sizeof(char *) + sizeof(const char *)));)
Package( TextFindIndex__,*(int*)(std) = TextFindIndex( *(const char **)(std), *(const char **)(std + sizeof(const char *)));std += sizeof(int);)
Package( TextToUpper__,*(const char **)(std) = TextToUpper( *(const char **)(std));std += sizeof(const char *);)
Package( TextToLower__,*(const char **)(std) = TextToLower( *(const char **)(std));std += sizeof(const char *);)
Package( TextToPascal__,*(const char **)(std) = TextToPascal( *(const char **)(std));std += sizeof(const char *);)
Package( TextToSnake__,*(const char **)(std) = TextToSnake( *(const char **)(std));std += sizeof(const char *);)
Package( TextToCamel__,*(const char **)(std) = TextToCamel( *(const char **)(std));std += sizeof(const char *);)
Package( TextToInteger__,*(int*)(std) = TextToInteger( *(const char **)(std));std += sizeof(int);)
Package( TextToFloat__,*(float*)(std) = TextToFloat( *(const char **)(std));std += sizeof(float);)
Package( DrawLine3D__,DrawLine3D( *(Vector3 *)(std), *(Vector3 *)(std + sizeof(Vector3 )), *(Color *)(std + sizeof(Vector3 ) + sizeof(Vector3 )));)
Package( DrawPoint3D__,DrawPoint3D( *(Vector3 *)(std), *(Color *)(std + sizeof(Vector3 )));)
Package( DrawCircle3D__,DrawCircle3D( *(Vector3 *)(std), *(float *)(std + sizeof(Vector3 )), *(Vector3 *)(std + sizeof(Vector3 ) + sizeof(float )), *(float *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(Vector3 )), *(Color *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(Vector3 ) + sizeof(float )));)
Package( DrawTriangle3D__,DrawTriangle3D( *(Vector3 *)(std), *(Vector3 *)(std + sizeof(Vector3 )), *(Vector3 *)(std + sizeof(Vector3 ) + sizeof(Vector3 )), *(Color *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(Vector3 )));)
Package( DrawTriangleStrip3D__,DrawTriangleStrip3D( *(const Vector3 **)(std), *(int *)(std + sizeof(const Vector3 *)), *(Color *)(std + sizeof(const Vector3 *) + sizeof(int )));)
Package( DrawCube__,DrawCube( *(Vector3 *)(std), *(float *)(std + sizeof(Vector3 )), *(float *)(std + sizeof(Vector3 ) + sizeof(float )), *(float *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(float )), *(Color *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(float ) + sizeof(float )));)
Package( DrawCubeV__,DrawCubeV( *(Vector3 *)(std), *(Vector3 *)(std + sizeof(Vector3 )), *(Color *)(std + sizeof(Vector3 ) + sizeof(Vector3 )));)
Package( DrawCubeWires__,DrawCubeWires( *(Vector3 *)(std), *(float *)(std + sizeof(Vector3 )), *(float *)(std + sizeof(Vector3 ) + sizeof(float )), *(float *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(float )), *(Color *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(float ) + sizeof(float )));)
Package( DrawCubeWiresV__,DrawCubeWiresV( *(Vector3 *)(std), *(Vector3 *)(std + sizeof(Vector3 )), *(Color *)(std + sizeof(Vector3 ) + sizeof(Vector3 )));)
Package( DrawSphere__,DrawSphere( *(Vector3 *)(std), *(float *)(std + sizeof(Vector3 )), *(Color *)(std + sizeof(Vector3 ) + sizeof(float )));)
Package( DrawSphereEx__,DrawSphereEx( *(Vector3 *)(std), *(float *)(std + sizeof(Vector3 )), *(int *)(std + sizeof(Vector3 ) + sizeof(float )), *(int *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(int )), *(Color *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(int ) + sizeof(int )));)
Package( DrawSphereWires__,DrawSphereWires( *(Vector3 *)(std), *(float *)(std + sizeof(Vector3 )), *(int *)(std + sizeof(Vector3 ) + sizeof(float )), *(int *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(int )), *(Color *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(int ) + sizeof(int )));)
Package( DrawCylinder__,DrawCylinder( *(Vector3 *)(std), *(float *)(std + sizeof(Vector3 )), *(float *)(std + sizeof(Vector3 ) + sizeof(float )), *(float *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(float )), *(int *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(float ) + sizeof(float )), *(Color *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(float ) + sizeof(float ) + sizeof(int )));)
Package( DrawCylinderEx__,DrawCylinderEx( *(Vector3 *)(std), *(Vector3 *)(std + sizeof(Vector3 )), *(float *)(std + sizeof(Vector3 ) + sizeof(Vector3 )), *(float *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float )), *(int *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float ) + sizeof(float )), *(Color *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float ) + sizeof(float ) + sizeof(int )));)
Package( DrawCylinderWires__,DrawCylinderWires( *(Vector3 *)(std), *(float *)(std + sizeof(Vector3 )), *(float *)(std + sizeof(Vector3 ) + sizeof(float )), *(float *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(float )), *(int *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(float ) + sizeof(float )), *(Color *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(float ) + sizeof(float ) + sizeof(int )));)
Package( DrawCylinderWiresEx__,DrawCylinderWiresEx( *(Vector3 *)(std), *(Vector3 *)(std + sizeof(Vector3 )), *(float *)(std + sizeof(Vector3 ) + sizeof(Vector3 )), *(float *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float )), *(int *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float ) + sizeof(float )), *(Color *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float ) + sizeof(float ) + sizeof(int )));)
Package( DrawCapsule__,DrawCapsule( *(Vector3 *)(std), *(Vector3 *)(std + sizeof(Vector3 )), *(float *)(std + sizeof(Vector3 ) + sizeof(Vector3 )), *(int *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float )), *(int *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float ) + sizeof(int )), *(Color *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float ) + sizeof(int ) + sizeof(int )));)
Package( DrawCapsuleWires__,DrawCapsuleWires( *(Vector3 *)(std), *(Vector3 *)(std + sizeof(Vector3 )), *(float *)(std + sizeof(Vector3 ) + sizeof(Vector3 )), *(int *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float )), *(int *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float ) + sizeof(int )), *(Color *)(std + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float ) + sizeof(int ) + sizeof(int )));)
Package( DrawPlane__,DrawPlane( *(Vector3 *)(std), *(Vector2 *)(std + sizeof(Vector3 )), *(Color *)(std + sizeof(Vector3 ) + sizeof(Vector2 )));)
Package( DrawRay__,DrawRay( *(Ray *)(std), *(Color *)(std + sizeof(Ray )));)
Package( DrawGrid__,DrawGrid( *(int *)(std), *(float *)(std + sizeof(int )));)
Package( LoadModel__,*(Model*)(std) = LoadModel( *(const char **)(std));std += sizeof(Model);)
Package( LoadModelFromMesh__,*(Model*)(std) = LoadModelFromMesh( *(Mesh *)(std));std += sizeof(Model);)
Package( IsModelValid__,*(bool*)(std) = IsModelValid( *(Model *)(std));std += sizeof(bool);)
Package( UnloadModel__,UnloadModel( *(Model *)(std));)
Package( GetModelBoundingBox__,*(BoundingBox*)(std) = GetModelBoundingBox( *(Model *)(std));std += sizeof(BoundingBox);)
Package( DrawModel__,DrawModel( *(Model *)(std), *(Vector3 *)(std + sizeof(Model )), *(float *)(std + sizeof(Model ) + sizeof(Vector3 )), *(Color *)(std + sizeof(Model ) + sizeof(Vector3 ) + sizeof(float )));)
Package( DrawModelEx__,DrawModelEx( *(Model *)(std), *(Vector3 *)(std + sizeof(Model )), *(Vector3 *)(std + sizeof(Model ) + sizeof(Vector3 )), *(float *)(std + sizeof(Model ) + sizeof(Vector3 ) + sizeof(Vector3 )), *(Vector3 *)(std + sizeof(Model ) + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float )), *(Color *)(std + sizeof(Model ) + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float ) + sizeof(Vector3 )));)
Package( DrawModelWires__,DrawModelWires( *(Model *)(std), *(Vector3 *)(std + sizeof(Model )), *(float *)(std + sizeof(Model ) + sizeof(Vector3 )), *(Color *)(std + sizeof(Model ) + sizeof(Vector3 ) + sizeof(float )));)
Package( DrawModelWiresEx__,DrawModelWiresEx( *(Model *)(std), *(Vector3 *)(std + sizeof(Model )), *(Vector3 *)(std + sizeof(Model ) + sizeof(Vector3 )), *(float *)(std + sizeof(Model ) + sizeof(Vector3 ) + sizeof(Vector3 )), *(Vector3 *)(std + sizeof(Model ) + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float )), *(Color *)(std + sizeof(Model ) + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float ) + sizeof(Vector3 )));)
Package( DrawModelPoints__,DrawModelPoints( *(Model *)(std), *(Vector3 *)(std + sizeof(Model )), *(float *)(std + sizeof(Model ) + sizeof(Vector3 )), *(Color *)(std + sizeof(Model ) + sizeof(Vector3 ) + sizeof(float )));)
Package( DrawModelPointsEx__,DrawModelPointsEx( *(Model *)(std), *(Vector3 *)(std + sizeof(Model )), *(Vector3 *)(std + sizeof(Model ) + sizeof(Vector3 )), *(float *)(std + sizeof(Model ) + sizeof(Vector3 ) + sizeof(Vector3 )), *(Vector3 *)(std + sizeof(Model ) + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float )), *(Color *)(std + sizeof(Model ) + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(float ) + sizeof(Vector3 )));)
Package( DrawBoundingBox__,DrawBoundingBox( *(BoundingBox *)(std), *(Color *)(std + sizeof(BoundingBox )));)
Package( DrawBillboard__,DrawBillboard( *(Camera *)(std), *(Texture2D *)(std + sizeof(Camera )), *(Vector3 *)(std + sizeof(Camera ) + sizeof(Texture2D )), *(float *)(std + sizeof(Camera ) + sizeof(Texture2D ) + sizeof(Vector3 )), *(Color *)(std + sizeof(Camera ) + sizeof(Texture2D ) + sizeof(Vector3 ) + sizeof(float )));)
Package( DrawBillboardRec__,DrawBillboardRec( *(Camera *)(std), *(Texture2D *)(std + sizeof(Camera )), *(Rectangle *)(std + sizeof(Camera ) + sizeof(Texture2D )), *(Vector3 *)(std + sizeof(Camera ) + sizeof(Texture2D ) + sizeof(Rectangle )), *(Vector2 *)(std + sizeof(Camera ) + sizeof(Texture2D ) + sizeof(Rectangle ) + sizeof(Vector3 )), *(Color *)(std + sizeof(Camera ) + sizeof(Texture2D ) + sizeof(Rectangle ) + sizeof(Vector3 ) + sizeof(Vector2 )));)
Package( DrawBillboardPro__,DrawBillboardPro( *(Camera *)(std), *(Texture2D *)(std + sizeof(Camera )), *(Rectangle *)(std + sizeof(Camera ) + sizeof(Texture2D )), *(Vector3 *)(std + sizeof(Camera ) + sizeof(Texture2D ) + sizeof(Rectangle )), *(Vector3 *)(std + sizeof(Camera ) + sizeof(Texture2D ) + sizeof(Rectangle ) + sizeof(Vector3 )), *(Vector2 *)(std + sizeof(Camera ) + sizeof(Texture2D ) + sizeof(Rectangle ) + sizeof(Vector3 ) + sizeof(Vector3 )), *(Vector2 *)(std + sizeof(Camera ) + sizeof(Texture2D ) + sizeof(Rectangle ) + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(Vector2 )), *(float *)(std + sizeof(Camera ) + sizeof(Texture2D ) + sizeof(Rectangle ) + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(Vector2 ) + sizeof(Vector2 )), *(Color *)(std + sizeof(Camera ) + sizeof(Texture2D ) + sizeof(Rectangle ) + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(Vector2 ) + sizeof(Vector2 ) + sizeof(float )));)
Package( UploadMesh__,UploadMesh( *(Mesh **)(std), *(bool *)(std + sizeof(Mesh *)));)
Package( UpdateMeshBuffer__,UpdateMeshBuffer( *(Mesh *)(std), *(int *)(std + sizeof(Mesh )), *(const void **)(std + sizeof(Mesh ) + sizeof(int )), *(int *)(std + sizeof(Mesh ) + sizeof(int ) + sizeof(const void *)), *(int *)(std + sizeof(Mesh ) + sizeof(int ) + sizeof(const void *) + sizeof(int )));)
Package( UnloadMesh__,UnloadMesh( *(Mesh *)(std));)
Package( DrawMesh__,DrawMesh( *(Mesh *)(std), *(Material *)(std + sizeof(Mesh )), *(Matrix *)(std + sizeof(Mesh ) + sizeof(Material )));)
Package( DrawMeshInstanced__,DrawMeshInstanced( *(Mesh *)(std), *(Material *)(std + sizeof(Mesh )), *(const Matrix **)(std + sizeof(Mesh ) + sizeof(Material )), *(int *)(std + sizeof(Mesh ) + sizeof(Material ) + sizeof(const Matrix *)));)
Package( GetMeshBoundingBox__,*(BoundingBox*)(std) = GetMeshBoundingBox( *(Mesh *)(std));std += sizeof(BoundingBox);)
Package( GenMeshTangents__,GenMeshTangents( *(Mesh **)(std));)
Package( ExportMesh__,*(bool*)(std) = ExportMesh( *(Mesh *)(std), *(const char **)(std + sizeof(Mesh )));std += sizeof(bool);)
Package( ExportMeshAsCode__,*(bool*)(std) = ExportMeshAsCode( *(Mesh *)(std), *(const char **)(std + sizeof(Mesh )));std += sizeof(bool);)
Package( GenMeshPoly__,*(Mesh*)(std) = GenMeshPoly( *(int *)(std), *(float *)(std + sizeof(int )));std += sizeof(Mesh);)
Package( GenMeshPlane__,*(Mesh*)(std) = GenMeshPlane( *(float *)(std), *(float *)(std + sizeof(float )), *(int *)(std + sizeof(float ) + sizeof(float )), *(int *)(std + sizeof(float ) + sizeof(float ) + sizeof(int )));std += sizeof(Mesh);)
Package( GenMeshCube__,*(Mesh*)(std) = GenMeshCube( *(float *)(std), *(float *)(std + sizeof(float )), *(float *)(std + sizeof(float ) + sizeof(float )));std += sizeof(Mesh);)
Package( GenMeshSphere__,*(Mesh*)(std) = GenMeshSphere( *(float *)(std), *(int *)(std + sizeof(float )), *(int *)(std + sizeof(float ) + sizeof(int )));std += sizeof(Mesh);)
Package( GenMeshHemiSphere__,*(Mesh*)(std) = GenMeshHemiSphere( *(float *)(std), *(int *)(std + sizeof(float )), *(int *)(std + sizeof(float ) + sizeof(int )));std += sizeof(Mesh);)
Package( GenMeshCylinder__,*(Mesh*)(std) = GenMeshCylinder( *(float *)(std), *(float *)(std + sizeof(float )), *(int *)(std + sizeof(float ) + sizeof(float )));std += sizeof(Mesh);)
Package( GenMeshCone__,*(Mesh*)(std) = GenMeshCone( *(float *)(std), *(float *)(std + sizeof(float )), *(int *)(std + sizeof(float ) + sizeof(float )));std += sizeof(Mesh);)
Package( GenMeshTorus__,*(Mesh*)(std) = GenMeshTorus( *(float *)(std), *(float *)(std + sizeof(float )), *(int *)(std + sizeof(float ) + sizeof(float )), *(int *)(std + sizeof(float ) + sizeof(float ) + sizeof(int )));std += sizeof(Mesh);)
Package( GenMeshKnot__,*(Mesh*)(std) = GenMeshKnot( *(float *)(std), *(float *)(std + sizeof(float )), *(int *)(std + sizeof(float ) + sizeof(float )), *(int *)(std + sizeof(float ) + sizeof(float ) + sizeof(int )));std += sizeof(Mesh);)
Package( GenMeshHeightmap__,*(Mesh*)(std) = GenMeshHeightmap( *(Image *)(std), *(Vector3 *)(std + sizeof(Image )));std += sizeof(Mesh);)
Package( GenMeshCubicmap__,*(Mesh*)(std) = GenMeshCubicmap( *(Image *)(std), *(Vector3 *)(std + sizeof(Image )));std += sizeof(Mesh);)
Package( LoadMaterials__,*(Material **)(std) = LoadMaterials( *(const char **)(std), *(int **)(std + sizeof(const char *)));std += sizeof(Material *);)
Package( LoadMaterialDefault__,*(Material*)(std) = LoadMaterialDefault();std += sizeof(Material);)
Package( IsMaterialValid__,*(bool*)(std) = IsMaterialValid( *(Material *)(std));std += sizeof(bool);)
Package( UnloadMaterial__,UnloadMaterial( *(Material *)(std));)
Package( SetMaterialTexture__,SetMaterialTexture( *(Material **)(std), *(int *)(std + sizeof(Material *)), *(Texture2D *)(std + sizeof(Material *) + sizeof(int )));)
Package( SetModelMeshMaterial__,SetModelMeshMaterial( *(Model **)(std), *(int *)(std + sizeof(Model *)), *(int *)(std + sizeof(Model *) + sizeof(int )));)
Package( LoadModelAnimations__,*(ModelAnimation **)(std) = LoadModelAnimations( *(const char **)(std), *(int **)(std + sizeof(const char *)));std += sizeof(ModelAnimation *);)
Package( UpdateModelAnimation__,UpdateModelAnimation( *(Model *)(std), *(ModelAnimation *)(std + sizeof(Model )), *(int *)(std + sizeof(Model ) + sizeof(ModelAnimation )));)
Package( UpdateModelAnimationBones__,UpdateModelAnimationBones( *(Model *)(std), *(ModelAnimation *)(std + sizeof(Model )), *(int *)(std + sizeof(Model ) + sizeof(ModelAnimation )));)
Package( UnloadModelAnimation__,UnloadModelAnimation( *(ModelAnimation *)(std));)
Package( UnloadModelAnimations__,UnloadModelAnimations( *(ModelAnimation **)(std), *(int *)(std + sizeof(ModelAnimation *)));)
Package( IsModelAnimationValid__,*(bool*)(std) = IsModelAnimationValid( *(Model *)(std), *(ModelAnimation *)(std + sizeof(Model )));std += sizeof(bool);)
Package( CheckCollisionSpheres__,*(bool*)(std) = CheckCollisionSpheres( *(Vector3 *)(std), *(float *)(std + sizeof(Vector3 )), *(Vector3 *)(std + sizeof(Vector3 ) + sizeof(float )), *(float *)(std + sizeof(Vector3 ) + sizeof(float ) + sizeof(Vector3 )));std += sizeof(bool);)
Package( CheckCollisionBoxes__,*(bool*)(std) = CheckCollisionBoxes( *(BoundingBox *)(std), *(BoundingBox *)(std + sizeof(BoundingBox )));std += sizeof(bool);)
Package( CheckCollisionBoxSphere__,*(bool*)(std) = CheckCollisionBoxSphere( *(BoundingBox *)(std), *(Vector3 *)(std + sizeof(BoundingBox )), *(float *)(std + sizeof(BoundingBox ) + sizeof(Vector3 )));std += sizeof(bool);)
Package( GetRayCollisionSphere__,*(RayCollision*)(std) = GetRayCollisionSphere( *(Ray *)(std), *(Vector3 *)(std + sizeof(Ray )), *(float *)(std + sizeof(Ray ) + sizeof(Vector3 )));std += sizeof(RayCollision);)
Package( GetRayCollisionBox__,*(RayCollision*)(std) = GetRayCollisionBox( *(Ray *)(std), *(BoundingBox *)(std + sizeof(Ray )));std += sizeof(RayCollision);)
Package( GetRayCollisionMesh__,*(RayCollision*)(std) = GetRayCollisionMesh( *(Ray *)(std), *(Mesh *)(std + sizeof(Ray )), *(Matrix *)(std + sizeof(Ray ) + sizeof(Mesh )));std += sizeof(RayCollision);)
Package( GetRayCollisionTriangle__,*(RayCollision*)(std) = GetRayCollisionTriangle( *(Ray *)(std), *(Vector3 *)(std + sizeof(Ray )), *(Vector3 *)(std + sizeof(Ray ) + sizeof(Vector3 )), *(Vector3 *)(std + sizeof(Ray ) + sizeof(Vector3 ) + sizeof(Vector3 )));std += sizeof(RayCollision);)
Package( GetRayCollisionQuad__,*(RayCollision*)(std) = GetRayCollisionQuad( *(Ray *)(std), *(Vector3 *)(std + sizeof(Ray )), *(Vector3 *)(std + sizeof(Ray ) + sizeof(Vector3 )), *(Vector3 *)(std + sizeof(Ray ) + sizeof(Vector3 ) + sizeof(Vector3 )), *(Vector3 *)(std + sizeof(Ray ) + sizeof(Vector3 ) + sizeof(Vector3 ) + sizeof(Vector3 )));std += sizeof(RayCollision);)
Package( InitAudioDevice__,InitAudioDevice();)
Package( CloseAudioDevice__,CloseAudioDevice();)
Package( IsAudioDeviceReady__,*(bool*)(std) = IsAudioDeviceReady();std += sizeof(bool);)
Package( SetMasterVolume__,SetMasterVolume( *(float *)(std));)
Package( GetMasterVolume__,*(float*)(std) = GetMasterVolume();std += sizeof(float);)
Package( LoadWave__,*(Wave*)(std) = LoadWave( *(const char **)(std));std += sizeof(Wave);)
Package( LoadWaveFromMemory__,*(Wave*)(std) = LoadWaveFromMemory( *(const char **)(std), *(const unsigned char **)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(const unsigned char *)));std += sizeof(Wave);)
Package( IsWaveValid__,*(bool*)(std) = IsWaveValid( *(Wave *)(std));std += sizeof(bool);)
Package( LoadSound__,*(Sound*)(std) = LoadSound( *(const char **)(std));std += sizeof(Sound);)
Package( LoadSoundFromWave__,*(Sound*)(std) = LoadSoundFromWave( *(Wave *)(std));std += sizeof(Sound);)
Package( LoadSoundAlias__,*(Sound*)(std) = LoadSoundAlias( *(Sound *)(std));std += sizeof(Sound);)
Package( IsSoundValid__,*(bool*)(std) = IsSoundValid( *(Sound *)(std));std += sizeof(bool);)
Package( UpdateSound__,UpdateSound( *(Sound *)(std), *(const void **)(std + sizeof(Sound )), *(int *)(std + sizeof(Sound ) + sizeof(const void *)));)
Package( UnloadWave__,UnloadWave( *(Wave *)(std));)
Package( UnloadSound__,UnloadSound( *(Sound *)(std));)
Package( UnloadSoundAlias__,UnloadSoundAlias( *(Sound *)(std));)
Package( ExportWave__,*(bool*)(std) = ExportWave( *(Wave *)(std), *(const char **)(std + sizeof(Wave )));std += sizeof(bool);)
Package( ExportWaveAsCode__,*(bool*)(std) = ExportWaveAsCode( *(Wave *)(std), *(const char **)(std + sizeof(Wave )));std += sizeof(bool);)
Package( PlaySound__,PlaySound( *(Sound *)(std));)
Package( StopSound__,StopSound( *(Sound *)(std));)
Package( PauseSound__,PauseSound( *(Sound *)(std));)
Package( ResumeSound__,ResumeSound( *(Sound *)(std));)
Package( IsSoundPlaying__,*(bool*)(std) = IsSoundPlaying( *(Sound *)(std));std += sizeof(bool);)
Package( SetSoundVolume__,SetSoundVolume( *(Sound *)(std), *(float *)(std + sizeof(Sound )));)
Package( SetSoundPitch__,SetSoundPitch( *(Sound *)(std), *(float *)(std + sizeof(Sound )));)
Package( SetSoundPan__,SetSoundPan( *(Sound *)(std), *(float *)(std + sizeof(Sound )));)
Package( WaveCopy__,*(Wave*)(std) = WaveCopy( *(Wave *)(std));std += sizeof(Wave);)
Package( WaveCrop__,WaveCrop( *(Wave **)(std), *(int *)(std + sizeof(Wave *)), *(int *)(std + sizeof(Wave *) + sizeof(int )));)
Package( WaveFormat__,WaveFormat( *(Wave **)(std), *(int *)(std + sizeof(Wave *)), *(int *)(std + sizeof(Wave *) + sizeof(int )), *(int *)(std + sizeof(Wave *) + sizeof(int ) + sizeof(int )));)
Package( LoadWaveSamples__,*(float **)(std) = LoadWaveSamples( *(Wave *)(std));std += sizeof(float *);)
Package( UnloadWaveSamples__,UnloadWaveSamples( *(float **)(std));)
Package( LoadMusicStream__,*(Music*)(std) = LoadMusicStream( *(const char **)(std));std += sizeof(Music);)
Package( LoadMusicStreamFromMemory__,*(Music*)(std) = LoadMusicStreamFromMemory( *(const char **)(std), *(const unsigned char **)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(const unsigned char *)));std += sizeof(Music);)
Package( IsMusicValid__,*(bool*)(std) = IsMusicValid( *(Music *)(std));std += sizeof(bool);)
Package( UnloadMusicStream__,UnloadMusicStream( *(Music *)(std));)
Package( PlayMusicStream__,PlayMusicStream( *(Music *)(std));)
Package( IsMusicStreamPlaying__,*(bool*)(std) = IsMusicStreamPlaying( *(Music *)(std));std += sizeof(bool);)
Package( UpdateMusicStream__,UpdateMusicStream( *(Music *)(std));)
Package( StopMusicStream__,StopMusicStream( *(Music *)(std));)
Package( PauseMusicStream__,PauseMusicStream( *(Music *)(std));)
Package( ResumeMusicStream__,ResumeMusicStream( *(Music *)(std));)
Package( SeekMusicStream__,SeekMusicStream( *(Music *)(std), *(float *)(std + sizeof(Music )));)
Package( SetMusicVolume__,SetMusicVolume( *(Music *)(std), *(float *)(std + sizeof(Music )));)
Package( SetMusicPitch__,SetMusicPitch( *(Music *)(std), *(float *)(std + sizeof(Music )));)
Package( SetMusicPan__,SetMusicPan( *(Music *)(std), *(float *)(std + sizeof(Music )));)
Package( GetMusicTimeLength__,*(float*)(std) = GetMusicTimeLength( *(Music *)(std));std += sizeof(float);)
Package( GetMusicTimePlayed__,*(float*)(std) = GetMusicTimePlayed( *(Music *)(std));std += sizeof(float);)
Package( LoadAudioStream__,*(AudioStream*)(std) = LoadAudioStream( *(unsigned int *)(std), *(unsigned int *)(std + sizeof(unsigned int )), *(unsigned int *)(std + sizeof(unsigned int ) + sizeof(unsigned int )));std += sizeof(AudioStream);)
Package( IsAudioStreamValid__,*(bool*)(std) = IsAudioStreamValid( *(AudioStream *)(std));std += sizeof(bool);)
Package( UnloadAudioStream__,UnloadAudioStream( *(AudioStream *)(std));)
Package( UpdateAudioStream__,UpdateAudioStream( *(AudioStream *)(std), *(const void **)(std + sizeof(AudioStream )), *(int *)(std + sizeof(AudioStream ) + sizeof(const void *)));)
Package( IsAudioStreamProcessed__,*(bool*)(std) = IsAudioStreamProcessed( *(AudioStream *)(std));std += sizeof(bool);)
Package( PlayAudioStream__,PlayAudioStream( *(AudioStream *)(std));)
Package( PauseAudioStream__,PauseAudioStream( *(AudioStream *)(std));)
Package( ResumeAudioStream__,ResumeAudioStream( *(AudioStream *)(std));)
Package( IsAudioStreamPlaying__,*(bool*)(std) = IsAudioStreamPlaying( *(AudioStream *)(std));std += sizeof(bool);)
Package( StopAudioStream__,StopAudioStream( *(AudioStream *)(std));)
Package( SetAudioStreamVolume__,SetAudioStreamVolume( *(AudioStream *)(std), *(float *)(std + sizeof(AudioStream )));)
Package( SetAudioStreamPitch__,SetAudioStreamPitch( *(AudioStream *)(std), *(float *)(std + sizeof(AudioStream )));)
Package( SetAudioStreamPan__,SetAudioStreamPan( *(AudioStream *)(std), *(float *)(std + sizeof(AudioStream )));)
Package( SetAudioStreamBufferSizeDefault__,SetAudioStreamBufferSizeDefault( *(int *)(std));)
Package( SetAudioStreamCallback__,SetAudioStreamCallback( *(AudioStream *)(std), *(AudioCallback *)(std + sizeof(AudioStream )));)
Package( AttachAudioStreamProcessor__,AttachAudioStreamProcessor( *(AudioStream *)(std), *(AudioCallback *)(std + sizeof(AudioStream )));)
Package( DetachAudioStreamProcessor__,DetachAudioStreamProcessor( *(AudioStream *)(std), *(AudioCallback *)(std + sizeof(AudioStream )));)
Package( AttachAudioMixedProcessor__,AttachAudioMixedProcessor( *(AudioCallback *)(std));)
Package( DetachAudioMixedProcessor__,DetachAudioMixedProcessor( *(AudioCallback *)(std));)
