Package( time__,*(time_t*)(std) = time( *(time_t **)(std));std += sizeof(time_t);)
Package( difftime__,*(double*)(std) = difftime( *(time_t *)(std), *(time_t *)(std + sizeof(time_t )));std += sizeof(double);)
Package( localtime__,*(struct tm **)(std) = localtime( *(const time_t **)(std));std += sizeof(struct tm *);)
Package( localtime_s__,*(errno_t*)(std) = localtime_s( *(struct tm **)(std), *(const time_t **)(std + sizeof(struct tm *)));std += sizeof(errno_t);)
Package( gmtime__,*(struct tm **)(std) = gmtime( *(const time_t **)(std));std += sizeof(struct tm *);)
Package( gmtime_s__,*(errno_t*)(std) = gmtime_s( *(struct tm **)(std), *(const time_t **)(std + sizeof(struct tm *)));std += sizeof(errno_t);)
Package( ctime__,*(char **)(std) = ctime( *(const time_t **)(std));std += sizeof(char *);)
Package( ctime_s__,*(errno_t*)(std) = ctime_s( *(char **)(std), *(size_t *)(std + sizeof(char *)), *(const time_t **)(std + sizeof(char *) + sizeof(size_t )));std += sizeof(errno_t);)
Package( mktime__,*(time_t*)(std) = mktime( *(struct tm **)(std));std += sizeof(time_t);)
Package( _mkgmtime__,*(time_t*)(std) = _mkgmtime( *(struct tm **)(std));std += sizeof(time_t);)
