Package( remove__,*(int*)(std) = remove( *(const char **)(std));std += sizeof(int);)
Package( rename__,*(int*)(std) = rename( *(const char **)(std), *(const char **)(std + sizeof(const char *)));std += sizeof(int);)
Package( tmpfile__,*(FILE **)(std) = tmpfile();std += sizeof(FILE *);)
Package( tmpnam__,*(char **)(std) = tmpnam( *(char **)(std));std += sizeof(char *);)
Package( fclose__,*(int*)(std) = fclose( *(FILE **)(std));std += sizeof(int);)
Package( fflush__,*(int*)(std) = fflush( *(FILE **)(std));std += sizeof(int);)
Package( fopen__,*(FILE **)(std) = fopen( *(const char **)(std), *(const char **)(std + sizeof(const char *)));std += sizeof(FILE *);)
Package( freopen__,*(FILE **)(std) = freopen( *(const char **)(std), *(const char **)(std + sizeof(const char *)), *(FILE **)(std + sizeof(const char *) + sizeof(const char *)));std += sizeof(FILE *);)
Package( setbuf__,setbuf( *(FILE **)(std), *(char **)(std + sizeof(FILE *)));)
Package( setvbuf__,*(int*)(std) = setvbuf( *(FILE **)(std), *(char **)(std + sizeof(FILE *)), *(int *)(std + sizeof(FILE *) + sizeof(char *)), *(size_t *)(std + sizeof(FILE *) + sizeof(char *) + sizeof(int )));std += sizeof(int);)
Package( printf__,*(int*)(std) = printf( *(const char **)(std), *(int *)(std + sizeof(const char *)));std += sizeof(int);)
Package( scanf__,*(int*)(std) = scanf( *(const char **)(std), *(int **)(std + sizeof(const char *)));std += sizeof(int);)
Package( snprintf__,*(int*)(std) = snprintf( *(char **)(std), *(size_t *)(std + sizeof(char *)), *(const char **)(std + sizeof(char *) + sizeof(size_t )), *(int *)(std + sizeof(char *) + sizeof(size_t ) + sizeof(const char *)));std += sizeof(int);)
Package( sprintf__,*(int*)(std) = sprintf( *(char **)(std), *(const char **)(std + sizeof(char *)), *(int *)(std + sizeof(char *) + sizeof(const char *)));std += sizeof(int);)
Package( sscanf__,*(int*)(std) = sscanf( *(const char **)(std), *(const char **)(std + sizeof(const char *)), *(int **)(std + sizeof(const char *) + sizeof(const char *)));std += sizeof(int);)
Package( vfprintf__,*(int*)(std) = vfprintf( *(FILE **)(std), *(const char **)(std + sizeof(FILE *)), *(va_list *)(std + sizeof(FILE *) + sizeof(const char *)));std += sizeof(int);)
Package( vfscanf__,*(int*)(std) = vfscanf( *(FILE **)(std), *(const char **)(std + sizeof(FILE *)), *(va_list *)(std + sizeof(FILE *) + sizeof(const char *)));std += sizeof(int);)
Package( vprintf__,*(int*)(std) = vprintf( *(const char **)(std), *(va_list *)(std + sizeof(const char *)));std += sizeof(int);)
Package( vscanf__,*(int*)(std) = vscanf( *(const char **)(std), *(va_list *)(std + sizeof(const char *)));std += sizeof(int);)
Package( vsnprintf__,*(int*)(std) = vsnprintf( *(char **)(std), *(size_t *)(std + sizeof(char *)), *(const char **)(std + sizeof(char *) + sizeof(size_t )), *(va_list *)(std + sizeof(char *) + sizeof(size_t ) + sizeof(const char *)));std += sizeof(int);)
Package( vsprintf__,*(int*)(std) = vsprintf( *(char **)(std), *(const char **)(std + sizeof(char *)), *(va_list *)(std + sizeof(char *) + sizeof(const char *)));std += sizeof(int);)
Package( vsscanf__,*(int*)(std) = vsscanf( *(const char **)(std), *(const char **)(std + sizeof(const char *)), *(va_list *)(std + sizeof(const char *) + sizeof(const char *)));std += sizeof(int);)
Package( fgetc__,*(int*)(std) = fgetc( *(FILE **)(std));std += sizeof(int);)
Package( fgets__,*(char **)(std) = fgets( *(char **)(std), *(int *)(std + sizeof(char *)), *(FILE **)(std + sizeof(char *) + sizeof(int )));std += sizeof(char *);)
Package( fputc__,*(int*)(std) = fputc( *(int *)(std), *(FILE **)(std + sizeof(int )));std += sizeof(int);)
Package( fputs__,*(int*)(std) = fputs( *(const char **)(std), *(FILE **)(std + sizeof(const char *)));std += sizeof(int);)
Package( getc__,*(int*)(std) = getc( *(FILE **)(std));std += sizeof(int);)
Package( getchar__,*(int*)(std) = getchar();std += sizeof(int);)
Package( putc__,*(int*)(std) = putc( *(int *)(std), *(FILE **)(std + sizeof(int )));std += sizeof(int);)
Package( putchar__,*(int*)(std) = putchar( *(int *)(std));std += sizeof(int);)
Package( puts__,*(int*)(std) = puts( *(const char **)(std));std += sizeof(int);)
Package( ungetc__,*(int*)(std) = ungetc( *(int *)(std), *(FILE **)(std + sizeof(int )));std += sizeof(int);)
Package( fread__,*(size_t*)(std) = fread( *(void **)(std), *(size_t *)(std + sizeof(void *)), *(size_t *)(std + sizeof(void *) + sizeof(size_t )), *(FILE **)(std + sizeof(void *) + sizeof(size_t ) + sizeof(size_t )));std += sizeof(size_t);)
Package( fwrite__,*(size_t*)(std) = fwrite( *(const void **)(std), *(size_t *)(std + sizeof(const void *)), *(size_t *)(std + sizeof(const void *) + sizeof(size_t )), *(FILE **)(std + sizeof(const void *) + sizeof(size_t ) + sizeof(size_t )));std += sizeof(size_t);)
Package( fgetpos__,*(int*)(std) = fgetpos( *(FILE **)(std), *(fpos_t **)(std + sizeof(FILE *)));std += sizeof(int);)
Package( fseek__,*(int*)(std) = fseek( *(FILE **)(std), *(long int *)(std + sizeof(FILE *)), *(int *)(std + sizeof(FILE *) + sizeof(long int )));std += sizeof(int);)
Package( fsetpos__,*(int*)(std) = fsetpos( *(FILE **)(std), *(const fpos_t **)(std + sizeof(FILE *)));std += sizeof(int);)
Package( ftell__,*(long int*)(std) = ftell( *(FILE **)(std));std += sizeof(long int);)
Package( rewind__,rewind( *(FILE **)(std));)
Package( clearerr__,clearerr( *(FILE **)(std));)
Package( feof__,*(int*)(std) = feof( *(FILE **)(std));std += sizeof(int);)
Package( ferror__,*(int*)(std) = ferror( *(FILE **)(std));std += sizeof(int);)
Package( perror__,perror( *(const char **)(std));)
Package( fprintf__,*(int*)(std) = fprintf( *(FILE **)(std), *(const char **)(std + sizeof(FILE *)), *(int *)(std + sizeof(FILE *) + sizeof(const char *)));std += sizeof(int);)
Package( fscanf__,*(int*)(std) = fscanf( *(FILE **)(std), *(const char **)(std + sizeof(FILE *)), *(int **)(std + sizeof(FILE *) + sizeof(const char *)));std += sizeof(int);)
