Package( atof__,*(double*)(std) = atof( *(const char **)(std));std += sizeof(double);)
Package( atoi__,*(int*)(std) = atoi( *(const char **)(std));std += sizeof(int);)
Package( atol__,*(long int*)(std) = atol( *(const char **)(std));std += sizeof(long int);)
Package( atoll__,*(long long int*)(std) = atoll( *(const char **)(std));std += sizeof(long long int);)
Package( strtod__,*(double*)(std) = strtod( *(const char **)(std), *(char ***)(std + sizeof(const char *)));std += sizeof(double);)
Package( strtof__,*(float*)(std) = strtof( *(const char **)(std), *(char ***)(std + sizeof(const char *)));std += sizeof(float);)
Package( strtold__,*(long double*)(std) = strtold( *(const char **)(std), *(char ***)(std + sizeof(const char *)));std += sizeof(long double);)
Package( strtol__,*(long int*)(std) = strtol( *(const char **)(std), *(char ***)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(char **)));std += sizeof(long int);)
Package( strtoll__,*(long long int*)(std) = strtoll( *(const char **)(std), *(char ***)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(char **)));std += sizeof(long long int);)
Package( strtoul__,*(unsigned long int*)(std) = strtoul( *(const char **)(std), *(char ***)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(char **)));std += sizeof(unsigned long int);)
Package( strtoull__,*(unsigned long long int*)(std) = strtoull( *(const char **)(std), *(char ***)(std + sizeof(const char *)), *(int *)(std + sizeof(const char *) + sizeof(char **)));std += sizeof(unsigned long long int);)
Package( rand__,*(int*)(std) = rand();std += sizeof(int);)
Package( srand__,srand( *(unsigned int *)(std));)
Package( calloc__,*(void **)(std) = calloc( *(size_t *)(std), *(size_t *)(std + sizeof(size_t )));std += sizeof(void *);)
Package( free__,free( *(void **)(std));)
Package( malloc__,*(void **)(std) = malloc( *(size_t *)(std));std += sizeof(void *);)
Package( realloc__,*(void **)(std) = realloc( *(void **)(std), *(size_t *)(std + sizeof(void *)));std += sizeof(void *);)
Package( abort__,abort();)
Package( exit__,exit( *(int *)(std));)
Package( getenv__,*(char **)(std) = getenv( *(const char **)(std));std += sizeof(char *);)
Package( system__,*(int*)(std) = system( *(const char **)(std));std += sizeof(int);)
Package( abs__,*(int*)(std) = abs( *(int *)(std));std += sizeof(int);)
Package( labs__,*(long int*)(std) = labs( *(long int *)(std));std += sizeof(long int);)
Package( llabs__,*(long long int*)(std) = llabs( *(long long int *)(std));std += sizeof(long long int);)
Package( div__,*(div_t*)(std) = div( *(int *)(std), *(int *)(std + sizeof(int )));std += sizeof(div_t);)
Package( ldiv__,*(ldiv_t*)(std) = ldiv( *(long int *)(std), *(long int *)(std + sizeof(long int )));std += sizeof(ldiv_t);)
Package( lldiv__,*(lldiv_t*)(std) = lldiv( *(long long int *)(std), *(long long int *)(std + sizeof(long long int )));std += sizeof(lldiv_t);)
Package( mblen__,*(int*)(std) = mblen( *(const char **)(std), *(size_t *)(std + sizeof(const char *)));std += sizeof(int);)
Package( mbtowc__,*(int*)(std) = mbtowc( *(wchar_t **)(std), *(const char **)(std + sizeof(wchar_t *)), *(size_t *)(std + sizeof(wchar_t *) + sizeof(const char *)));std += sizeof(int);)
Package( wctomb__,*(int*)(std) = wctomb( *(char **)(std), *(wchar_t *)(std + sizeof(char *)));std += sizeof(int);)
Package( mbstowcs__,*(size_t*)(std) = mbstowcs( *(wchar_t **)(std), *(const char **)(std + sizeof(wchar_t *)), *(size_t *)(std + sizeof(wchar_t *) + sizeof(const char *)));std += sizeof(size_t);)
