Package( memcpy__,*(void **)(std) = memcpy( *(void **)(std), *(const void **)(std + sizeof(void *)), *(size_t *)(std + sizeof(void *) + sizeof(const void *)));std += sizeof(void *);)
Package( memccpy__,*(void **)(std) = memccpy( *(void **)(std), *(const void **)(std + sizeof(void *)), *(int *)(std + sizeof(void *) + sizeof(const void *)), *(size_t *)(std + sizeof(void *) + sizeof(const void *) + sizeof(int )));std += sizeof(void *);)
Package( memmove__,*(void **)(std) = memmove( *(void **)(std), *(const void **)(std + sizeof(void *)), *(size_t *)(std + sizeof(void *) + sizeof(const void *)));std += sizeof(void *);)
Package( strcpy__,*(char **)(std) = strcpy( *(char **)(std), *(const char **)(std + sizeof(char *)));std += sizeof(char *);)
Package( strncpy__,*(char **)(std) = strncpy( *(char **)(std), *(const char **)(std + sizeof(char *)), *(size_t *)(std + sizeof(char *) + sizeof(const char *)));std += sizeof(char *);)
Package( strdup__,*(char **)(std) = strdup( *(const char **)(std));std += sizeof(char *);)
Package( strcat__,*(char **)(std) = strcat( *(char **)(std), *(const char **)(std + sizeof(char *)));std += sizeof(char *);)
Package( strncat__,*(char **)(std) = strncat( *(char **)(std), *(const char **)(std + sizeof(char *)), *(size_t *)(std + sizeof(char *) + sizeof(const char *)));std += sizeof(char *);)
Package( memcmp__,*(int*)(std) = memcmp( *(const void **)(std), *(const void **)(std + sizeof(const void *)), *(size_t *)(std + sizeof(const void *) + sizeof(const void *)));std += sizeof(int);)
Package( strcmp__,*(int*)(std) = strcmp( *(const char **)(std), *(const char **)(std + sizeof(const char *)));std += sizeof(int);)
Package( strcoll__,*(int*)(std) = strcoll( *(const char **)(std), *(const char **)(std + sizeof(const char *)));std += sizeof(int);)
Package( strncmp__,*(int*)(std) = strncmp( *(const char **)(std), *(const char **)(std + sizeof(const char *)), *(size_t *)(std + sizeof(const char *) + sizeof(const char *)));std += sizeof(int);)
Package( strxfrm__,*(size_t*)(std) = strxfrm( *(char **)(std), *(const char **)(std + sizeof(char *)), *(size_t *)(std + sizeof(char *) + sizeof(const char *)));std += sizeof(size_t);)
Package( memchr__,*(void **)(std) = memchr( *(void **)(std), *(int *)(std + sizeof(void *)), *(size_t *)(std + sizeof(void *) + sizeof(int )));std += sizeof(void *);)
Package( strchr__,*(char **)(std) = strchr( *(char **)(std), *(int *)(std + sizeof(char *)));std += sizeof(char *);)
Package( strcspn__,*(size_t*)(std) = strcspn( *(const char **)(std), *(const char **)(std + sizeof(const char *)));std += sizeof(size_t);)
Package( strpbrk__,*(char **)(std) = strpbrk( *(char **)(std), *(const char **)(std + sizeof(char *)));std += sizeof(char *);)
Package( strrchr__,*(char **)(std) = strrchr( *(char **)(std), *(int *)(std + sizeof(char *)));std += sizeof(char *);)
Package( strspn__,*(size_t*)(std) = strspn( *(const char **)(std), *(const char **)(std + sizeof(const char *)));std += sizeof(size_t);)
Package( strstr__,*(char **)(std) = strstr( *(char **)(std), *(const char **)(std + sizeof(char *)));std += sizeof(char *);)
Package( strtok__,*(char **)(std) = strtok( *(char **)(std), *(const char **)(std + sizeof(char *)));std += sizeof(char *);)
Package( memset__,*(void **)(std) = memset( *(void **)(std), *(int *)(std + sizeof(void *)), *(size_t *)(std + sizeof(void *) + sizeof(int )));std += sizeof(void *);)
Package( strerror__,*(char **)(std) = strerror( *(int *)(std));std += sizeof(char *);)
Package( strlen__,*(size_t*)(std) = strlen( *(const char **)(std));std += sizeof(size_t);)
Package( strnlen__,*(size_t*)(std) = strnlen( *(const char **)(std), *(size_t *)(std + sizeof(const char *)));std += sizeof(size_t);)
