Package( isalpha__,*(int*)(std) = isalpha( *(int *)(std));std += sizeof(int);)
Package( isupper__,*(int*)(std) = isupper( *(int *)(std));std += sizeof(int);)
Package( islower__,*(int*)(std) = islower( *(int *)(std));std += sizeof(int);)
Package( isdigit__,*(int*)(std) = isdigit( *(int *)(std));std += sizeof(int);)
Package( isxdigit__,*(int*)(std) = isxdigit( *(int *)(std));std += sizeof(int);)
Package( isspace__,*(int*)(std) = isspace( *(int *)(std));std += sizeof(int);)
Package( ispunct__,*(int*)(std) = ispunct( *(int *)(std));std += sizeof(int);)
Package( isalnum__,*(int*)(std) = isalnum( *(int *)(std));std += sizeof(int);)
Package( isprint__,*(int*)(std) = isprint( *(int *)(std));std += sizeof(int);)
Package( isgraph__,*(int*)(std) = isgraph( *(int *)(std));std += sizeof(int);)
Package( iscntrl__,*(int*)(std) = iscntrl( *(int *)(std));std += sizeof(int);)
Package( toupper__,*(int*)(std) = toupper( *(int *)(std));std += sizeof(int);)
Package( _toupper__,*(int*)(std) = _toupper( *(int *)(std));std += sizeof(int);)
Package( tolower__,*(int*)(std) = tolower( *(int *)(std));std += sizeof(int);)
Package( _tolower__,*(int*)(std) = _tolower( *(int *)(std));std += sizeof(int);)
Package( _tolower_l__,*(int*)(std) = _tolower_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _isctype__,*(int*)(std) = _isctype( *(int *)(std), *(int *)(std + sizeof(int )));std += sizeof(int);)
Package( isblank__,*(int*)(std) = isblank( *(int *)(std));std += sizeof(int);)
Package( _isalpha_l__,*(int*)(std) = _isalpha_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _isupper_l__,*(int*)(std) = _isupper_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _islower_l__,*(int*)(std) = _islower_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _isdigit_l__,*(int*)(std) = _isdigit_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _isxdigit_l__,*(int*)(std) = _isxdigit_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _isspace_l__,*(int*)(std) = _isspace_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _ispunct_l__,*(int*)(std) = _ispunct_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _isalnum_l__,*(int*)(std) = _isalnum_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _isprint_l__,*(int*)(std) = _isprint_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _isgraph_l__,*(int*)(std) = _isgraph_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _iscntrl_l__,*(int*)(std) = _iscntrl_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _toupper_l__,*(int*)(std) = _toupper_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( _isctype_l__,*(int*)(std) = _isctype_l( *(int *)(std), *(int *)(std + sizeof(int )), *(_locale_t *)(std + sizeof(int ) + sizeof(int )));std += sizeof(int);)
Package( _isblank_l__,*(int*)(std) = _isblank_l( *(int *)(std), *(_locale_t *)(std + sizeof(int )));std += sizeof(int);)
Package( __isascii__,*(int*)(std) = __isascii( *(int *)(std));std += sizeof(int);)
Package( __toascii__,*(int*)(std) = __toascii( *(int *)(std));std += sizeof(int);)
Package( __iscsymf__,*(int*)(std) = __iscsymf( *(int *)(std));std += sizeof(int);)
Package( __iscsym__,*(int*)(std) = __iscsym( *(int *)(std));std += sizeof(int);)
